### ISSUE TITLE
icon-as-button missing styles

### ISSUE THREAD

**Issue by matikrk** [brainly/style-guide#1018]
Not all styles are defined in scss. or It's done baddly
Cases:
* Border + adaptive = bad border color
* action + adaptive + active = background is primary color not adaptive
* transparent + active + colors(adaptive, gray, gray-secondary, gray-light, dark ) = not defined
* icon-as-button have less amount of colors than icons

**Comment by kdzwinel** [comment]
@matikrk you were rebuilding it in react, any of these issues were fixed?

**Comment by matikrk** [comment]
there was issues on styles side. I only created all combinations in React and saw problems. Nothing was fixed
