### ISSUE TITLE
Flex-box for layouting

### ISSUE THREAD

**Issue by mr-mig** [brainly/style-guide#103]
I would propose to use `flexbox` styles for vertical and inline positioning of components (push to left/right/botton, centering) instead of relying on `inline-block` + `position`/`vertical-align`.

**Comment by mr-mig** [comment]
> Improve quality for styleguide components

**Comment by aju** [comment]
Is there anything else except checkbox-label that does not use flexbox (it has separate issue) Can we close it?
@mr-mig @kdzwinel @matzimowski @vergilius

**Comment by mr-mig** [comment]
Basically, everything laid in a row :)
Breadcrumbs, ckeckbox, radio, some buttons do not have holes, the page layouts are not using flexbox as well.
