### ISSUE TITLE
Designing containers

### ISSUE THREAD

**Issue by mr-mig** [brainly/style-guide#106]
We should bear in mind (and tell out designers), that any container should be designed for this cases:

* zero children
* one children
* many children

The same goes for text containers, it will help handle overflows.

**Comment by mr-mig** [comment]
Maybe this should be a separate container with correct item wrapping inside?
WDYT? 
@kdzwinel @matzimowski @aju @vergilius

**Comment by aju** [comment]
Maybe we can handle it with css ?

**Comment by mr-mig** [comment]
Yeah, its definitely to be solved with CSS. 
This is one of the aspects you need to keep in mind and add to README.

But I am wondering whether we can create a container with wrapping behaviour, which will be used in all other places so that we solve this problem only one.

**Comment by vergilius** [comment]
We discussed it with @kdzwinel and we agreed that this should be separate container with `__hole's` to be used across all components

**Comment by mr-mig** [comment]
It may be necessary to distinguish 3 types of "holes" in every container:

1. Title - the place where header goes. 
 - Should not have centering enabled, as some headers have to snap to top of the text box
 - May ruin vertical rhythm inside for headers
 - Always the first-child of its parent
2. Content - basic text. 
 - Should always honor vertical rhythm
3. Actions - buttons, avatars, etc
 - Always the last child of its parent
 - Should have vertical centering enabled
 - rhythm(2) height for bigger components

**Comment by vergilius** [comment]
@mr-mig I'm not sure about having only basic text in content, imho it could take just anything inside, text, other component etc.

**Comment by vergilius** [comment]
See also here: https://github.com/brainly/style-guide/issues/365

**Comment by aju** [comment]
I think we solved it with actions-list element that needs to be ported to style guide
