### ISSUE TITLE
Create set of font sizes

### ISSUE THREAD

**Issue by vergilius** [brainly/style-guide#108]
We need to make new font sizes for mobile devices and discuss it with designers.

**Comment by aju** [comment]
@mr-mig @vergilius can we close it?

**Comment by mr-mig** [comment]
No, we need to figure out whether we want to have different base font sizes for different devices... @JoannaWalusiak @JanuszSzewczyk 

If not - then close. If it is possible, but not now - then lets leave this issue opened and just move it out from backlog

**Comment by JanuszSzewczyk** [comment]
Only for BIT's. Other fonts should stay the same. We talked abouth this with @JoannaWalusiak and @aju right now

**Comment by aju** [comment]
@mr-mig bits are responsive by default so you can close it.
