### ISSUE TITLE
Fix button with stars

### ISSUE THREAD

**Issue by aju** [brainly/style-guide#116]
![screen shot 2015-08-04 at 18 08 42](https://cloud.githubusercontent.com/assets/316313/9065789/1f4dd5d6-3ad4-11e5-95e9-5b1db72991f3.png)
On hovering over first area one star should be active, on second 5 stars should be active

**Comment by matzimowski** [comment]
it works nice already:
![cd06039820c3ff3be040a5ee910d2bb0](https://cloud.githubusercontent.com/assets/1231144/16147809/c9803b42-3485-11e6-8bb5-5e66061bc862.gif)
i am closing it.

**Comment by aju** [comment]
@matzimowski button!

**Comment by matzimowski** [comment]
:*
