### ISSUE TITLE
subject icons should not be separate

### ISSUE THREAD

**Issue by kdzwinel** [brainly/style-guide#127]
IMO subject icons should be just added to the default icon set. I don't see any reason to keep them separate. Also, currently they are made using `background-image` instead of `content: ''` which makes it impossible to change their color (if we'll ever need that).

Andrzej's argument was that subjects are used only on the main page so we don't have to load them for ppl only visiting the question page reducing page size. Hovers, IMO that's a premature optimization and judging from the mocks, the assumption that subjects are used only on the main page wasn't true:

<img width="225" alt="screen shot 2015-08-05 at 18 09 10" src="https://cloud.githubusercontent.com/assets/985504/9090866/171605ae-3b9d-11e5-9042-acb6e9c8753f.png">

**Comment by mr-mig** [comment]
Will require figuring out the fallback strategy, implementing, refatoring related projects - 3 stars

**Comment by kdzwinel** [comment]
OK, so we had a bit of discussion on that and now I'm in favour of moving everything the other way instead - to the SVG sprite.

Why?
- we will deliver a much better experience to kids in indonesia/india/thailand where Opera Mini is ~20% of the market ( see #234 )
- Chris Coyer's list of pros: https://css-tricks.com/svg-sprites-use-better-icon-fonts/
- we already have a setup for SVG sprites (subjects) and we haven't seen any issues so far
- fontcustom is bulky and not reliable (we had some issues before)
- we can add colors with this technique: https://lincolnloop.com/blog/svg-sprites-and-icon-systems-are-super/
- this will also fix the centering issue - #115

**Comment by aju** [comment]
So we should embed whole SVG in top of the page and then reference it using "<use>" ?

**Comment by aju** [comment]
@kdzwinel have you made research about embedding svg?

**Comment by kdzwinel** [comment]
Small research, but yes. I intend to use technique mentioned in my previous comment: https://lincolnloop.com/blog/svg-sprites-and-icon-systems-are-super/ . It uses `<use>` as you mentioned today. Also, I learned that we can reference external files like so: ` <use xlink:href="/path/to/svgdef.svg#your-icon"></use>` which solves issue with caching.

**Comment by kdzwinel** [comment]
More research:

IE does not support external files in `<use>`, there is a polyfill though: https://github.com/jonathantneal/svg4everybody (see the bottom of the readme for some helpful tips on accessibility)

Example of SVG icon system: https://mcraiganthony.github.io/svg-icons/#

The good news is that above system seems to work on opera mini!
<img width="483" alt="screen shot 2015-09-08 at 22 53 41" src="https://cloud.githubusercontent.com/assets/985504/9747208/9e0a026e-567c-11e5-9cd5-e029986d0e99.png">

http://ianfeather.co.uk/ten-reasons-we-switched-from-an-icon-font-to-svg/

**Comment by aju** [comment]
@kdzwinel +1 for using polyfill.

The only issue I see now is that we need to reference this sprite somehow (know its path) and we are using now fingerprint to add some cache breaker for our resources.
I don't think its needed actually as we are using styleguide from cdn and with verion change path is already changed. As long as we don't store images in one folder we don't need to finger print them. WDYT ?
@mr-mig @matzimowski @vergilius

**Comment by aju** [comment]
My mistake I see images are served always from one folder so issue is how we reference correct filename in symfony (in order ot use <use>). We need probably to parse and cache rev-manifest.json file.

**Comment by kdzwinel** [comment]
Linked to the wrong article before: https://css-tricks.com/icon-fonts-vs-svg/

**Comment by aju** [comment]
Can we close it? I think we need separate issue for subject icons as they should be references with <use> not as background images to be consistent.
@kdzwinel @mr-mig  ?

**Comment by kdzwinel** [comment]
Closing. Follow up here: https://github.com/brainly/style-guide/issues/357
