### ISSUE TITLE
Select & Dropdown component differences

### ISSUE THREAD

**Issue by vergilius** [brainly/style-guide#1288]
Select and dropdown components have different API (accepts different data structures via props)
```
Select: 
const items = StatusList.map(status => ({value: status.id, text: status.name}));

Dropdown:
const items = RankingList.map(type => ({id: type.id.toString(), text: type.name}));
```

Both should accept the same source.

Also, picking selected value is different, one accepts ID, second accepts object (one of the items)

**Comment by kdzwinel** [comment]
Unify the API for both components.

**Comment by matikrk** [comment]
Dropdown should have API from Select
