### ISSUE TITLE
Action List setting line-height: 0;

### ISSUE THREAD

**Issue by matikrk** [brainly/style-guide#1305]
When using action list i got problem with CSS
This component have line-height: 0; and it's can cause problems with rendering multi line content inside holes.
I had problem when tried using it with bubbles:
<img width="587" alt="screen shot 2017-10-04 at 13 35 55" src="https://user-images.githubusercontent.com/17196505/31173782-26e628f2-a909-11e7-84d3-b0949a86e6b1.png">
Using sg-text inside bubble solved it, but this bug can be confusing.

**Comment by kdzwinel** [comment]
wrap text in sg-text, not a bug
