### ISSUE TITLE
change exporter constants naming in SG - TYPE

### ISSUE THREAD

**Issue by matikrk** [brainly/style-guide#1331]
In our code we have problem with all time renaming exports from SG components. 
Examples Icon.TYPE to ICON_TYPE, ButtonPrimary.TYPE to BUTTON_TYPE. Sometimes there is even camelCase naming - iconType
To avoid this we should change naming of it.

**Comment by aju** [comment]
In addition when reexporting name should stay the same. Example:
IconAsButton is reexporting ICON_TYPE property - it should keep same name in export
