### ISSUE TITLE
Improve interactive docs

### ISSUE THREAD

**Issue by burakukula** [brainly/style-guide#1336]
As we noticed, interactive docs could have more practical value for us.
For the moment, JSX would show us:

`<HeaderPrimary type="h2" size="small" color="light">We've got your back!</HeaderPrimary>`

But actually we would need it to display like:

`<HeaderPrimary type={TYPE.H2} size={SIZE.SMALL} color={COLOR.LIGHT}>We've got your back!</HeaderPrimary>`

This way we could just copy&paste the code into the project, without changes.

**Comment by kdzwinel** [comment]
https://microsoft.github.io/YamUI/
