### ISSUE TITLE
Research option to group imports from style-guide

### ISSUE THREAD

**Issue by vergilius** [brainly/style-guide#1342]
At current moment, we often see a lot of imports from style-guide for single component.
We would like to group them (how to do that is part of research).

```
import Link from 'style-guide/src/components/text/Link';
import ActionList from 'style-guide/src/components/action-list/ActionList';
import ActionListHole from 'style-guide/src/components/action-list/ActionListHole';
```

vs 

`import {Link, ActionList, ActionListHole} from 'style-guide';`

**Comment by matzimowski** [comment]
already done in https://github.com/brainly/style-guide/pull/1588
