### ISSUE TITLE
Fix search on iOS

### ISSUE THREAD

**Issue by burakukula** [brainly/style-guide#1375]
![image uploaded from ios 1](https://user-images.githubusercontent.com/4272331/34936019-2769e750-f9e0-11e7-8deb-8e119ef09d33.png)
![image uploaded from ios 2](https://user-images.githubusercontent.com/4272331/34936020-2783bd74-f9e0-11e7-8cf6-b4c5850d311a.png)

**Comment by kdzwinel** [comment]
`-webkit-appearance: none;` ?

**Comment by kdzwinel** [comment]
http://jsbin.com/polazaviwe/edit?html,css - fix confirmed!
