### ISSUE TITLE
header interactive demo broken

### ISSUE THREAD

**Issue by kdzwinel** [brainly/style-guide#1401]
Around version 120-121 we broke the header interactive demo

<img width="750" alt="screen shot 2018-02-13 at 23 10 22" src="https://user-images.githubusercontent.com/985504/36176520-22e50418-1113-11e8-9390-f099e81e2832.png">

@matzimowski

**Comment by matzimowski** [comment]
this component was removed from interactive page here: https://github.com/brainly/style-guide/pull/1538
i am closing this one.
