### ISSUE TITLE
Add hide overflow option for actions list hole

### ISSUE THREAD

**Issue by aju** [brainly/style-guide#1416]
```
.sg-actions-list > .sg-actions-list__hole--hide-overflow {
  overflow: hidden;
}
```
why:
<img width="436" alt="screen shot 2018-03-19 at 13 05 01" src="https://user-images.githubusercontent.com/316313/37594682-38ac53aa-2b76-11e8-8c7e-a6fa809d487e.png">
to make possible middle TOC section

**Comment by kdzwinel** [comment]
maybe some kind of overflow helper we can wrap the text in? 🤔

**Comment by matzimowski** [comment]
not valid anymore
