### ISSUE TITLE
Fix white corners in Card and Toplayer

### ISSUE THREAD

**Issue by kdzwinel** [brainly/style-guide#1429]
![screen shot 2018-04-10 at 15 17 38](https://user-images.githubusercontent.com/985504/38559088-5d92a71a-3cd2-11e8-8f76-5573f745eaf6.png)

![screen shot 2018-04-10 at 15 16 55](https://user-images.githubusercontent.com/985504/38559086-5d77907e-3cd2-11e8-9312-eee7cd4fea57.png)

we need "transparent background" option on both Card and Toplayer

**Comment by matzimowski** [comment]
fixed https://github.com/brainly/style-guide/pull/1430
