### ISSUE TITLE
Global components descriptions

### ISSUE THREAD

**Issue by vergilius** [brainly/style-guide#1458]
We should have at least short descriptions for components, so people who look at it and want to use it could find best component.

For example, you can achieve similar results using `Box` and `Toplayer` or even `Card`.
The same goes for headers, and texts

**Comment by tomasz-sodzawiczny** [comment]
Good idea! Defining clear semantics of components is actually one of the main points of having a style guide. ;)

Where and in what form should we keep that description? It should be shared with the design team, it has to be used by the UX designers in the first place.

**Comment by vergilius** [comment]
I agree.

Maybe we should start with something so simple like describing components vs containters.

@aju @burakukula wdyt?
