### ISSUE TITLE
Add option to center layout content

### ISSUE THREAD

**Issue by wasilakkf** [brainly/style-guide#1475]
```
.sg-layout__content--center {
  margin: 0 auto;
}
```
It is already used in code but there was no issue for this. There are cases when we have only one column which is not 100% wide and we want to center it. On large screens main column takes by default (100% - asideContentWidth) and starts from left.

It is used for example for contact box:

Without:
<img width="1438" alt="screen shot 2018-08-08 at 13 49 46" src="https://user-images.githubusercontent.com/29686716/43835373-03143f62-9b12-11e8-8b2a-7553806f0c59.png">

With:
<img width="1429" alt="screen shot 2018-08-08 at 13 49 54" src="https://user-images.githubusercontent.com/29686716/43835377-0611f54c-9b12-11e8-93df-cda7dfa6f1ab.png">

**Comment by aju** [comment]
@wasilakkf please add more info where its needed and why (screenshot would be nice ;) )

**Comment by aju** [comment]
,
