### ISSUE TITLE
'Rating' and 'Thanks' buttons do not scale correctly

### ISSUE THREAD

**Issue by kdzwinel** [brainly/style-guide#150]
<img width="227" alt="screen shot 2015-08-12 at 11 56 55" src="https://cloud.githubusercontent.com/assets/985504/9221273/6a7c1638-40e9-11e5-8eec-2b216ad8df0f.png">

**Comment by mr-mig** [comment]
Do you mean "zoom" or what?

**Comment by kdzwinel** [comment]
they should have a min-width IMO, right now they become unreadable when squeezed

**Comment by mr-mig** [comment]
How do you "squeeze" them at all? 
Are you using browser zoom?

**Comment by matzimowski** [comment]
this problem doesn't occur anymore.
these buttons are not squeezed at all:)
i am closing it.
