### ISSUE TITLE
Add code quality tools 

### ISSUE THREAD

**Issue by mr-mig** [brainly/style-guide#153]
Smth like https://github.com/brigade/scss-lint to eliminate unused variables/duplicates...

**Comment by kdzwinel** [comment]
@aju Closed?

**Comment by aju** [comment]
I will close it with PR that has code style fixes (and I need to hook it up to CI)

**Comment by aju** [comment]
@kdzwinel @mr-mig @vergilius @matzimowski 
I will close this one if you know other tools that we need or integrations please add separate issue for them
