### ISSUE TITLE
Action list - to right, missing spacing

### ISSUE THREAD

**Issue by seahindeniz** [brainly/style-guide#1600]
Hi!

Action-list component has `--to-right` modifier but it does not contains/respects the `__hole`'s  `--no-spacing` or `--spaced-xsmall` or `--spaced-small` or `--spaced-large` modifiers. It should have more control over spacing modifiers.

https://github.com/brainly/style-guide/blob/87a724e84a7784a9799d907f75d44346e8ea6f32/src/components/action-list/action-list.scss#L89-L100

**Comment by burakukula** [comment]
Merged, I'm closing this issue.
