### ISSUE TITLE
White color on icon in the Button component 

### ISSUE THREAD

**Issue by seahindeniz** [brainly/style-guide#1609]
Hi!

There is a problem with the `Button` component and it's not ready for a white and transparent background color.

`primary-inverted`, `secondary`, `link-button`, `link-button-peach`, ` link-button-mustard`, `destructive` and `warning` 
I'll continue to call this modifiers as cripple modifiers :stuck_out_tongue:  (no offense please)

Right now, the `color` property of the cripple modifiers are configured to respect background color, to increase readability and visibility. But the color of `fill` property of `sg-button__icon` modifier is statically defined with white color and it's not respects to background color of the button element.
https://github.com/brainly/style-guide/blob/82e102957927e9f563fbd9e7b9d26f1a42ad811a/src/components/buttons/_buttons.scss#L41-L42

Well,
this configuration ends up like this of course:
![image](https://user-images.githubusercontent.com/5789670/62083764-673a7680-b260-11e9-9c9d-282d8794ff13.png)

You can read texts in both button elements but can't see the icons because it's white :roll_eyes:
Of course you can see the icon when button is in hover stage and you need to focus harder if you have healthy eyes :eyes:
So there is no point to have icon inside a button if it's modified with a cripple modifier.

I hope this will be considered as a bug, not a feature :sweat_smile:

Thanks in advance :slightly_smiling_face:

**Comment by burakukula** [comment]
@seahindeniz Hey! You can specify the color of the icon inside the button like the following:

```
<Button icon={<Icon type="answer" color="dark" size={24} />} type="primary-inverted">Answer</Button>
```

We have some default icon color specified, but this is not a blocker for you to use a different one. If you use `adaptive` the behavior of the class would be `adaptive` like the namespace suggests.

We will fix some issue in the interactive part, so you would have the option to specify the color of the icon inside the button in the future. And this can be considered a bug.

Btw, I don't really get it why you call them `cripple modifiers` and I would prefer to stick to standard nomenclature if you don't mind.

**Comment by seahindeniz** [comment]
Thanks again @burakukula I should've focus more on coloring the icon.

Sorry about the naming, that is just a humorized name to reference those specific modifiers that I need to mention in more than once. The humor in the name is just, I didn't know that we have an option to colorize icon before you and I thought they were created like that and can't be modified without using special treatment outside of standart. So that is why I choose actually :slightly_smiling_face:

**Comment by burakukula** [comment]
@seahindeniz sure, no worries, all good 🙂
If you have any other issues feel free to reach out to us. And we will try to fix the interactive part of SG to handle icons colors asap.
I'll keep you posted! 🤓
