### ISSUE TITLE
Additional margin* props 

### ISSUE THREAD

**Issue by mpacholec** [brainly/style-guide#1614]
`<Flex />` component has `margin*` props with predefined values.

IMHO those should also go to components as `Headline` & `Text` etc.

WDYT?

**Comment by burakukula** [comment]
@mpacholec I am not really sure about this solution. I guess it can be achieved by using flex margins. I image you would like to have something like: `<p class="sg-text sg-text--margin-left-xs">some text</p>`?

**Comment by mpacholec** [comment]
> @mpacholec I am not really sure about this solution. I guess it can be achieved by using flex margins. I image you would like to have something like: `<p class="sg-text sg-text--margin-left-xs">some text</p>`?

Yup that is what I meant. I think it would be nice to have unified margin/padding props across all* components. 

e.g.
```jsx
<Text marginTop="xxs">SOME TEXT</Text>
```
