### ISSUE TITLE
<FlashMessage /> should accept children

### ISSUE THREAD

**Issue by mpacholec** [brainly/style-guide#1622]
Currently `FlashMessage` accepts `text` prop
IMHO it would be great to have the possibility to pass more complex components e.g. `<Link />` to FlashMessage

```jsx
<FlashMessage>
  <Text>
     SOME MESSAGE
  </Text>
  <Link>ClickMe</Link>
</FlashMessage>
```

**Comment by clxandstuff** [comment]
Closing as outdated
