### ISSUE TITLE
Regarding the new icons

### ISSUE THREAD

**Issue by seahindeniz** [brainly/style-guide#1624]
Hi!

In the version [147.1.0](https://github.com/brainly/style-guide/releases/tag/v147.1.0), @matzimowski  has added new icons. Specifically the `std-profile_view` and `std-reload` and we know that this new icons are also contained in the latest set of icons file([std-icons-4fd63f0d49.js](https://styleguide.brainly.com/images/std-icons-4fd63f0d49.js)).
So currently Brainly web app has the latest style guide([v147.2.0](https://github.com/brainly/style-guide/releases/tag/v147.2.0)) but the std-icons file isn't updated yet and currently, it has the older [std-icons-12f84055d5.js](https://styleguide.brainly.com/images/std-icons-4fd63f0d49.js) file.

So my question is, do you have release time for the latest icons file? So that new icons can be used safely.

**Comment by matzimowski** [comment]
hello @seahindeniz,
you can use the safely already.

this update u mentioned was not necessary for us in Brainly web app at that point.

but we have just started using one of updated icons, so the script containing std-icons has been updated and this change is being deployed now.

**Comment by seahindeniz** [comment]
Thanks! Brainly web has the newest std-icons now and closing the issue
