### ISSUE TITLE
Avatar border

### ISSUE THREAD

**Issue by seahindeniz** [brainly/style-guide#1635]
Hi

Can we have new options to specify border color and size for the Avatar component. It has border option to specify the border with only white color but it doesn't have option to specify color or size. Maybe it would be good to have these options. 

If you agree to have these options, it should also have an option to specify different border colors and sizes for each corner.

Like:
```
border?: true, // This will apply the default border color 
borderSize: "large" | 4 | true, // Current sizing is limited to avatar size so option to specify size.

border?: "peach", // this will apply peach color to all corners

// Rest will apply default or different color to corners.
border-top?: "" | "peach",
border-right?: "" | "mustard",
border-bottom?: "" | "mint",
border-left?: "" | "lavender",
```

Expected result:
![image](https://user-images.githubusercontent.com/5789670/63852340-b92a0580-c9a0-11e9-9531-a36ae36dafb8.png)
```
border-width: 4px;
border-top-color: #ff604b;
border-right-color: #eda600;
border-bottom-color: #40bd7e;
border-left-color: #435fee;
```
**or**

![image](https://user-images.githubusercontent.com/5789670/63852500-132acb00-c9a1-11e9-96ca-a4d34141bcb2.png)
```
border-width: 3px;
border-color: #ff604b;
```

**Comment by clxandstuff** [comment]
Closing as outdated
