### ISSUE TITLE
Badge animation breaks avatars

### ISSUE THREAD

**Issue by kdzwinel** [brainly/style-guide#165]
While badge animation (katie) is running avatars are square instead of round. Reproducible on the styleguide components page.
 
<img width="537" alt="screen shot 2015-08-14 at 10 04 26" src="https://cloud.githubusercontent.com/assets/985504/9269638/e0aafd0a-426b-11e5-9c67-60d020f5533a.png">

**Comment by mr-mig** [comment]
We are blocked by the 3rd-party issue...

**Comment by aju** [comment]
@kdzwinel can we close it as we applied fix that resolved this bug?

**Comment by aju** [comment]
Closing this one
