### ISSUE TITLE
Content Style Guide

### ISSUE THREAD

**Issue by serahrono** [brainly/style-guide#1664]
Hi there 👋 

Your Style Guide is great, I appreciate the work you've put into it. 

I have a two-part question about content in it:
- should headers in the style guide be in `Camel Case` or `Regular sentence case`?
- should contributions to content in the style guide use EN-GB or EN-US?

**Comment by burakukula** [comment]
@serahrono thanks a lot! ❤️
I think we go with a regular sentence case in EN-US.  Hope this will help. If anything comes up, let us know and we will try to help out. 🙂
