### ISSUE TITLE
Support multiple selection for Select component

### ISSUE THREAD

**Issue by seahindeniz** [brainly/style-guide#1701]
Can you consider adding multiple selection ability to Select component? 

This happens when Select component has `multiple` attribute true
![image](https://user-images.githubusercontent.com/5789670/66397470-91d54800-e9e4-11e9-8ff9-a2da2b14b298.png)

**Comment by clxandstuff** [comment]
We develop new select component. It is close to be released and it will support multiple selection. Stay tuned!
https://github.com/brainly/style-guide/pull/2665
