### ISSUE TITLE
Rendering issue on Eodev

### ISSUE THREAD

**Issue by seahindeniz** [brainly/style-guide#1716]
Could you please check the link below? The miss-rendered `em` tags affects all components inside of it.
https://eodev.com/gorev/16731542

![image](https://user-images.githubusercontent.com/5789670/73951986-7a18bc80-490f-11ea-88ef-acca1e84677f.png)

**Comment by matzimowski** [comment]
@seahindeniz thanks for reporting it. i will report it as a bug in our internal reporting system.
