### ISSUE TITLE
Add onKeyDown to every onClick for accessibility

### ISSUE THREAD

**Issue by ElaLukaszewicz** [brainly/style-guide#1723]
Add onKeyDown to every onClick for accessibility:
everywhere where onClick is added we should add onKeyDown and on enter passed onClick should be fired

**Comment by clxandstuff** [comment]
Hi @ElaLukaszewicz.
If I understand correctly, this is the default browser behavior when you focus elements and use Enter or Space keys. Please reopen if you think we need any additional default onKeyDown handler behavior.
