### ISSUE TITLE
Clarify the approach for mobile/non-mobile components

### ISSUE THREAD

**Issue by mr-mig** [brainly/style-guide#174]
If the element is a part of container, then the hole in the container can have mint-hidden-for-desktop applied
If the element has two different forms on mobile/desktop, or it has different parts visible - then it's better to hide those parts with the breakpoints inside the component

Does it make sense?

See here:
https://github.com/brainly/symfony/pull/1679/files#diff-9aa9b1ef9b373bcfcaa5a2900c65fce6R8

**Comment by vergilius** [comment]
We currently use `sg-hide-for-*` for that kind of situations.
