### ISSUE TITLE
The new error message for input

### ISSUE THREAD

**Issue by seahindeniz** [brainly/style-guide#1761]
Hello @anna-wro @matzimowski @ElaLukaszewicz @bartoszlorek 

I have reviewed the changes and I would like to ask; can `Input` return one type element instead of having overload?

After https://github.com/brainly/style-guide/commit/687c54f21144e9949fbbdbc0ef39c89941cd898c, a wrapped input element returns if it's `errorMessage` prop has value and is invalid otherwise returns a single input element.

What about returning the input wrapper regardless, no matter what its props is to have a single type of structure. Would that be a bad practice?

Like changing `errorMessage` to `helpText` or `tipText` to show a small message/text like this?
![image](https://user-images.githubusercontent.com/5789670/77769629-26943680-7055-11ea-9fbe-82ad2e0a4eb4.png)

**Comment by coderitual** [comment]
I am closing the issue as not much has happened in here
