### ISSUE TITLE
Â char on sg-breadcrumb-list__element 

### ISSUE THREAD

**Issue by seahindeniz** [brainly/style-guide#1787]
Possibly similar to this issue https://stackoverflow.com/questions/4146933/insert-special-character-using-before-pseudo-class-in-css

![image](https://user-images.githubusercontent.com/5789670/80511922-708a7800-8985-11ea-95a0-b0127961b2d3.png)

This issue is not something that always appears and refreshing the page once or twice may solve the rendering issue.
I didn't look for what is causing this. Needs to be investigated

**Comment by seahindeniz** [comment]
Although possible solution would be replacing the `·(middle dot)` with its unicode format `\00B7` 
https://github.com/brainly/style-guide/blob/d6f3291a86510fade5d5b0c23cfe7a2dac20f95b/src/components/breadcrumbs/_breadcrumbs.scss#L15

I have tested this locally and I can't absolutely confirm this is can be a fix

**Comment by matzimowski** [comment]
👏
