### ISSUE TITLE
Add display: inline to Breadcrumb elements

### ISSUE THREAD

**Issue by anna-wro** [brainly/style-guide#1796]
Needed for the new profile page
<img width="276" alt="Screenshot 2020-05-21 at 16 39 12" src="https://user-images.githubusercontent.com/9083292/82649658-db903d00-9c19-11ea-889d-e50043cf9fdb.png">
<img width="276" alt="Screenshot 2020-05-21 at 16 41 05" src="https://user-images.githubusercontent.com/9083292/82649662-dc28d380-9c19-11ea-9066-0a84c2334b7a.png">

```
.sg-breadcrumb-list--inline-items .sg-breadcrumb-list__element {
  display: inline;
}
```

**Comment by matzimowski** [comment]
👏
