### ISSUE TITLE
Add transparent labels 

### ISSUE THREAD

**Issue by anna-wro** [brainly/style-guide#1799]
Needed for answer item footer

<img width="683" alt="Screenshot 2020-05-26 at 12 54 01" src="https://user-images.githubusercontent.com/9083292/82898547-cd178d80-9f59-11ea-9204-3bf6d69667d3.png">

with gray secondary text
```
.sg-label--transparent {
  background-color: transparent;
}
```
```
.sg-label--gray-secondary {
  .sg-text {
    color: $graySecondary;
  }

  .sg-icon__svg {
    fill: $graySecondary;
  }
}
```

**Comment by seahindeniz** [comment]
@anna-wro I just noticed this and wanted to let you know. Seems link this one has resolved 🙂

**Comment by coderitual** [comment]
Can we close this @anna-wro @seahindeniz ?

**Comment by anna-wro** [comment]
Yup
