### ISSUE TITLE
Create box with border and header (see example)

### ISSUE THREAD

**Issue by aju** [brainly/style-guide#181]
![screen shot 2015-08-18 at 11 47 07](https://cloud.githubusercontent.com/assets/316313/9327135/eee53d96-459e-11e5-8dfe-14f53b92c775.png)

**Comment by kdzwinel** [comment]
To me, that's a box with a content box inside.

We have the same scenario with Katie:

<img width="357" alt="screen shot 2015-09-02 at 11 40 10" src="https://cloud.githubusercontent.com/assets/985504/9627879/7b8af5be-5167-11e5-82df-7a06c5a98127.png">

content box inside a bubble

**Comment by mr-mig** [comment]
I am afraid that `content-box` will have those margins as well

**Comment by mr-mig** [comment]
But please go ahead with `mint-box` (or maybe `mint-card`). 
We will refactor those things if anything
