### ISSUE TITLE
Add spaced breadcrumb elements

### ISSUE THREAD

**Issue by anna-wro** [brainly/style-guide#1811]
...after a successful test of user profile

normal:
<img width="675" alt="Screenshot 2020-06-02 at 11 25 50" src="https://user-images.githubusercontent.com/9083292/83503844-02752b80-a4c4-11ea-8ab6-5ca875b9b619.png">

spaced:
<img width="675" alt="Screenshot 2020-06-02 at 11 25 39" src="https://user-images.githubusercontent.com/9083292/83503836-ff7a3b00-a4c3-11ea-8cd0-016e2ee3f193.png">

```
.sg-breadcrumb-list--spaced {
  .sg-breadcrumb-list__element::after {
    padding: 0 4px;
  }
}
```

**Comment by coderitual** [comment]
Hey @anna-wro! Is that still valid?

**Comment by anna-wro** [comment]
> Hey @anna-wro! Is that still valid?

Hey. It's still used in our code in 3 components

**Comment by coderitual** [comment]
@anna-wro thanks for your swift feedback!

**Comment by clxandstuff** [comment]
Hi @anna-wro 

We can work on it but first I need to know, whether this extra space should be default or new variant?
What do you think @coderitual ?
