### ISSUE TITLE
Edge17 icon size issue, min-height needed

### ISSUE THREAD

**Issue by anna-wro** [brainly/style-guide#1813]
with min-height:
<img width="676" alt="Screenshot 2020-06-05 at 11 01 34" src="https://user-images.githubusercontent.com/9083292/83859257-eff62e80-a71d-11ea-89c2-cf1c30587edd.png">

without:
<img width="676" alt="Screenshot 2020-06-05 at 10 57 19" src="https://user-images.githubusercontent.com/9083292/83859254-ef5d9800-a71d-11ea-926c-1143133544ec.png">

**Comment by clxandstuff** [comment]
Hi @anna-wro 

Tested on latest Edge 92.0.902.62 and it works fine. I'm unable to test it on that very old edge though. .

![Screenshot 2021-08-31 at 14 41 51](https://user-images.githubusercontent.com/25419830/131504344-b5c05a51-df81-41f9-9396-01a68d23d9ab.png)

**Comment by clxandstuff** [comment]
@anna-wro 
I'm closing this issue. If you will still some issue please open new issue.
