### ISSUE TITLE
"â€¢" chars in the content of .brn-horizontal-list__item:after

### ISSUE THREAD

**Issue by seahindeniz** [brainly/style-guide#1885]
Hi

Same problem on the issue #1787 is also appears on the `.brn-horizontal-list__item:after`

Here is a screenshot
![image](https://user-images.githubusercontent.com/5789670/89044932-5761e080-d353-11ea-82c0-1e374e1a0f27.png)

Replacing the "â€¢" with it's unicode format `\00B7` would be a better approach
![image](https://user-images.githubusercontent.com/5789670/89045818-d60b4d80-d354-11ea-91ea-27ff0785ce4e.png)

I assume those random-like characters are not intentional so it's better to change it to `"\2022"`.

**Comment by matzimowski** [comment]
thanks for reporting @seahindeniz 
hm, but from what i can see we already use unicode here: https://github.com/brainly/style-guide/blob/master/src/components/breadcrumbs/_breadcrumbs.scss#L15

could u let us know what browser are u using so we could try to debug it, please?

**Comment by seahindeniz** [comment]
Hi @matzimowski 

Yes, I have checked and can confirm that Breadcrumbs with Unicode, has no trouble with rendering. I was pointing to another modifier class which is not related to Style Guide I think.
The left arrow points to the modifier that I've mentioned in the previous post. The right arrow is pointing the `.sg-breadcrumb-list__element:after`
![image](https://user-images.githubusercontent.com/5789670/89044932-5761e080-d353-11ea-82c0-1e374e1a0f27.png)

I'm currently using Google Chrome 85.0.4183.121 but 2 months ago, the version number may have slightly different. Something like 84.0.4147.110, I'm not sure.

**Comment by matzimowski** [comment]
oh, i got it now, thank you @seahindeniz 
So it's the issue on the website, not in style-guide.
We'll try to take care of it.

**Comment by matzimowski** [comment]
I checked, it should be solved already from 10 Aug.
i am closing this one.
