### ISSUE TITLE
Toplayer should accept ref prop

### ISSUE THREAD

**Issue by ElaLukaszewicz** [brainly/style-guide#1891]
Toplayer should accept ref prop for example for 'useClickOutside' hook

**Comment by clxandstuff** [comment]
Hi @ElaKrk
I think that, we could handle it by adding `onOutsideClick` prop. What do you think? Is that going to work for you? 😃 

@coderitual any arguments for using ref instead dedicated prop for such functionality? 🤔

**Comment by clxandstuff** [comment]
Closing as outdated. Confirmed with @ElaLukaszewicz.
