### ISSUE TITLE
EM/REM for text and paddings

### ISSUE THREAD

**Issue by mr-mig** [brainly/style-guide#192]
http://trentwalton.com/2012/06/19/fluid-type/
https://bugsnag.com/blog/responsive-typography-with-rems

See the example: http://jsfiddle.net/25gCt/4/embedded/result/

**Comment by JoannaWalusiak** [comment]
Changes in typography - Styleguide
http://typecast.com/QhQQkkddGr/share/87eeaf5d967424f871d1236edad36ee3d46a85b6KrPQgjrbw

1em = 16px

From the top of the question page

Info-task - ENGLISH  •  HIGHSCHOOL  •  10 PTS
p.info-date {
   font-size: 0.8em;  
   line-height: 1em;
   font-family: „ProximaNovaExtrabold";
   text-transform: uppercase;
   letter-spacing: 1px;
   margin: 0em 0em 1em 0em;
   color: rgba(187, 189, 191, 1);

Question text big (first 3 lines):
p.question-big {
   font-size: 1.75em;
   margin: 0em 0em 1em 0em;
   line-height: 2em;
   text-align: left;

Question text medium + Answer text + Stream questions text
p.answer-text {
   font-size: 1.125em;   18px
   line-height: 1.5em;   24px
   margin: 0em 0em 1em 0em;
   text-align: justify; (or not:)

Blue actions - Comment  •  Follow  •  Report
p.action {
   font-size: 1em;
   line-height: 1em;
   color: rgba(91, 184, 255, 1);
   font-family: „ProximaNovaExtrabold";
   text-transform: capitalize;
   margin: 0em 0em 3em 0em;

Headlines - Your Answer, Answers, New Questions
p.headline {
   font-size: 1em;
   line-height: 1em;
   font-family: "ProximaNovaExtrabold";
   text-transform: uppercase;
   letter-spacing: 1px;
   margin: 0px 0px 2em 0px;

BIT - What do you want to know and others
p.bit {
   font-size: 3.625em;  58px;
   line-height: 3em;  48px;
   text-transform: uppercase;
   font-family: „ProximaNovaBlack";
   letter-spacing: -1px;
   color: rgba(167, 230, 198, 1);
   margin: 0em 0em 1em 0em;

Buttons
p.button-addq {
   font-family: „ProximaNovaExtrabold";
   font-size: 1em;
   line-height: 3em;
   margin: 0em 0em 3em 0em;
   background-color: rgba(110, 214, 160, 1);
   -webkit-border-radius: 1.5em;
   -o-border-radius: 1.5em;
   -moz-border-radius: 1.5em;
   -ms-border-radius: 1.5em;
   border-radius: 1.5em;
   padding: 0em 2em;
   width: 170px;
   text-transform: uppercase;
   color: rgba(255, 255, 255, 1);

Side stream questions text
p.question-small {
   font-family: „ProximaNovaRegular";
   font-size: 1em;
   line-height: 1.5em;
   margin: 0em 0em 1em 0em;

mobile view 320px
  margin: 2em 1.5em 0px 1.5em; 

Is that clear? :dancer:

**Comment by mr-mig** [comment]
The font palette is:

h.1
  font-size: 58px;
  line-height: 48px;

h.2
  font-size: 28px;
  line-height: 32px;

h.3
  font-size: 18px
  line-height: 24px

h.4
  font-size: 16px;
  line-height: 24px;

h.5
  font-size: 16px;
  line-height: 16px;

h.6
  font-size: 13px;
  line-height: 16px;

default text
   16px 24px

**Comment by mr-mig** [comment]
Also, mind `letter-spacing` in Joanna's example!

**Comment by mr-mig** [comment]
So, after analysing the codebase I've decided to change `text-block`, `text-description`, `mint-text-bit` components according to the given example.

**Comment by mr-mig** [comment]
After discussion with @kdzwinel @matzimowski @vergilius we've decided to refactor those `text-*` components to a single `mint-text`.

Also `mint-text-bit` should be moved in the overview doc to `basics` next to text examples.

Everything TBD in scope of #13 and this issue,

**Comment by mr-mig** [comment]
On the other hand, I am wondering whether I should move `mint-text` to components and not `mint-text-bit` to basics.
As they both assume to be used as a component inside containers. 

Also, bit has a variation with logo and can scale down on mobile...
Which are seem to me to be more like attributes of “component”

We can visualize the font sizes in basics instead of `mint-text`
WDYT? @aju @kdzwinel @vergilius @matzimowski

**Comment by mr-mig** [comment]
Tried this thing with `cap-height=0.57`: https://gist.github.com/razwan/10662500
This approach seems to work only when `line-height` is always natural multiply of `baseline` :(

**Comment by mr-mig** [comment]
> Improve quality for styleguide components
