### ISSUE TITLE
Documentation Issue on Input Component

### ISSUE THREAD

**Issue by cattofiq** [brainly/style-guide#1926]
Hello, 

This input option checkbox must radio buttons. Because button in same time can not be valid and invalid. And some one try to check 2 option same tame page will broke and I think this is bad user experience for documentation. 

![Screen Shot 2020-09-24 at 09 01 32](https://user-images.githubusercontent.com/67333249/94103098-c71cb500-fe44-11ea-8806-8adf32268248.png)

After Check two option same time 

![Screen Shot 2020-09-24 at 09 05 36](https://user-images.githubusercontent.com/67333249/94103239-25e22e80-fe45-11ea-8b0b-c8b4c3f84f3b.png)

**Comment by coderitual** [comment]
Hey @cattofiq, thank for reporting this! I agree that allowing for this impossible state is wrong. At the same time this is what we have in our component and documentation just reflects the state of it. I am not entirely sure if fixing documentation only is a good approach. It looks like the revision should concern the component itself in the first place.

**Comment by cattofiq** [comment]
Yeah sure I'm agree with U :)

**Comment by coderitual** [comment]
Good point @cattofiq , we gonna look into improving documentation to at least warn users that there is a way to have an "impossible" state. While I still think that this throw we already is a good enough solution when using library I agree that documentation should handle that in more user friendly way.
