### ISSUE TITLE
Refactor repo layout

### ISSUE THREAD

**Issue by mr-mig** [brainly/style-guide#197]
To make the next step towards the componentization and mobile-first approach I would propose to reshuffle the components and refactore the overview.

* [x] Move components to separate folders, like `/components/avatar/styles.scss`
* [x] Create `index.html` in every component folder
* [ ] Refactor overview to contain 3 iframes for every component: `mobile`, `tablet` and `desktop` views
* [x] Use `index.html` from every component to fill corresponding iframes 
* [x] The last couple of steps can be automated via javascript generator/bundler (like webpack)

WDYT? @kdzwinel @aju @vergilius @matzimowski

**Comment by mr-mig** [comment]
@kdzwinel fixed?

**Comment by kdzwinel** [comment]
kinda, iframe's for all components are not in place, but you can create a separate issue for that and close this one
