### ISSUE TITLE
New size for button 

### ISSUE THREAD

**Issue by KaiDrolop** [brainly/style-guide#2042]
Hello,

It will be good to have a new size smaller than s

For exemple `sg-button sg-button--s sg-button--solid sg-button--icon-only` 

May be  a xs size will be a useful new size.
![image](https://user-images.githubusercontent.com/50515478/116989111-fc8e5880-acd9-11eb-89da-96eca81c3ebe.png)
![image](https://user-images.githubusercontent.com/50515478/117106675-f30ff980-ad88-11eb-9d6c-e669d883db1c.png)

Thanks

**Comment by coderitual** [comment]
hey @KaiDrolop
thank you for suggestion. At the moment we're not considering smaller button as we don't have any use case for that.

**Comment by coderitual** [comment]
Hey @KaiDrolop I'm closing the issue as this is not something we consider at the moment. Let me know if you would like to discuss it further
