### ISSUE TITLE
[Floating header MOBILE] Searching

### ISSUE THREAD

**Issue by JanuszSzewczyk** [brainly/style-guide#205]
On Chrome iOS 8.4.1 when you want to scroll back (you are e.g. at the bottom on the page and you scroll up a bit then if you tap on search input then keyboard is appearing header is fixing in strange way:
(i will add screen if I have one)

**Comment by mr-mig** [comment]
We do not support Chrome iOS yet, as the % of users in our traffic is very low.
Moved from backlog as low priority.

**Comment by aju** [comment]
@JanuszSzewczyk closing this one.
