### ISSUE TITLE
Label and text-overflow: ellipsis

### ISSUE THREAD

**Issue by matzimowski** [brainly/style-guide#2068]
we could consider adding a way to handle longer texts in labels using `text-overflow: ellipsis` option by default, i.e

<img width="232" alt="Screenshot 2021-06-22 at 18 36 30" src="https://user-images.githubusercontent.com/1231144/123093075-7e257b80-d42b-11eb-8f75-1f2e37e8afe6.png">

otherwise, it has to be handled manually (like [here](https://github.com/brainly/brainly-frontend/pull/15835)) and requires overriding style-guide related styles.

**Comment by patrycja-b** [comment]
I agree, it would be nice to have such option by default. 
We also are having problems with [long text in labels](http://brainly.test/textbook-solutions?subject=e7efba14-3b96-4aa2-b261-005016511fd1&class=8b720b51-01cb-4fb0-94c7-a1a7df62106e&board=13405017-5f4a-45f2-8815-6f85f33f9185&language=ef76ce81-ed32-49ce-a081-bb9f5b90deae) (we will fix it on our side for now).
