### ISSUE TITLE
Wrong JSX code in Boxes component

### ISSUE THREAD

**Issue by Lukaszbembenek** [brainly/style-guide#2080]
JSX code has some errors in Boxes component:
![Screenshot 2021-07-29 at 12 46 49](https://user-images.githubusercontent.com/51786143/127479601-37bc47ba-c9e4-4815-9d2f-409812121acc.png)

v190.0.0

**Comment by coderitual** [comment]
Hey @Lukaszbembenek , thanks for reporting this! I am happy to get PR with fixes if you would like to contribute.
