### ISSUE TITLE
Separators - add new color and refactor props

### ISSUE THREAD

**Issue by matikrk** [brainly/style-guide#2086]
Currently we have color defined with not the best way: 
```js
<SeparatorHorizontal white />
<SeparatorHorizontal grayDark />
```
we should change it to
```js
<SeparatorHorizontal color={colorVariable} />
```

color props should get values in a new way https://design.brainly.com/8adfd5f36/p/851b11-colors
like in https://design.brainly.com/8adfd5f36/p/851b11-colors
```js
<Spinner color="peach-700" />
```
When we refactor it we need to add the color `Gray-300` to it

And then we should be able to use it like this
```js
<SeparatorHorizontal color="gray-300" />
```

**Comment by domidomi** [comment]
@matikrk Spinner and both Separators components were refactored recently. You can see all available colors here:
https://style-guide.brainly.com/?path=/story/components-spinner--colors
and https://style-guide.brainly.com/?path=/story/components-separators-separatorhorizontal--colors. Let me know if you need more colors to be added
