### ISSUE TITLE
Select on Firefox 3x (tested on ff 33) has default arrow

### ISSUE THREAD

**Issue by vergilius** [brainly/style-guide#209]
Looks like `-moz-appearance` does not work in this case

![screen shot 2015-08-27 at 10 12 58](https://cloud.githubusercontent.com/assets/1142999/9515828/7310d010-4ca4-11e5-8fc2-daf2333cb995.png)

**Comment by kdzwinel** [comment]
I can't reproduce that on the latest firefox (40)

**Comment by kdzwinel** [comment]
@vergilius please retest, I can't reproduce it (tested on ubuntu and osx)

**Comment by vergilius** [comment]
Lets skip it, looks like it was a bug until ff 35 arrived: http://stackoverflow.com/questions/9620404/styling-a-select-element-in-firefox
