### ISSUE TITLE
Dialog component - elements have outline applied in Safari after opening Dialog

### ISSUE THREAD

**Issue by patrycja-b** [brainly/style-guide#2273]
There is an issue on Safari in Dialog component. 
- Button to close dialog is outlined by default when you open the dialog
<img width="392" alt="Screenshot 2022-01-27 at 13 41 25" src="https://user-images.githubusercontent.com/26112034/151360883-f44cfab5-4c4d-4fb5-9cda-b2aeff991774.png">

- Modal is outlined by default when you open the dialog - it happened for me only in [one component](https://github.com/brainly/brainly-frontend/blob/master/packages/components/src/TextbooksExerciseBookinfoTooltip/TextbooksExerciseBookinfoTooltip.tsx) - you can check it [here](https://brainly.test/textbook-solutions/q-1-zero-rational-number-write-form-p) by clicking on `i` icon (available only on mobile) but I suspect that it may be caused by some logic inside `useFocusTrap` function  used in`Dialog`
<img width="392" alt="Screenshot 2022-01-27 at 13 41 10" src="https://user-images.githubusercontent.com/26112034/151360877-d83e441e-621d-462c-800c-0cb4b94b1308.png">

Tested in: Safari v15.2

**Comment by katarzynatobis** [comment]
@patrycja-b It works as expected. When you open a dialog, focus should be moved to the first focusable element inside that dialog or, if there is no such item, whole dialog should be focused.

**Comment by patrycja-b** [comment]
@katarzynatobis ok, thanks for checking and explaining 👍
