### ISSUE TITLE
Dialog component - safari&VO lose focus when opening 2nd dialog

### ISSUE THREAD

**Issue by katarzynatobis** [brainly/style-guide#2278]
https://user-images.githubusercontent.com/60467496/151973337-bcd60ff8-e8d0-4934-b402-660a4da5cc0d.mov

**Comment by clxandstuff** [comment]
It is even worse. Focus trap is not working, tabbing forward stops on close button, tabbing backwards stops on proceed button.


Uploading Screen Recording 2023-03-14 at 17.49.14.mov…
