### ISSUE TITLE
Using / for division is deprecated

### ISSUE THREAD

**Issue by wasilakkf** [brainly/style-guide#2310]
Just a minor inconvenience when building an app that uses SG as those warnings can't be easily ignored/silenced. For example in tutoring:
![Screenshot 2022-02-17 at 08 59 57](https://user-images.githubusercontent.com/29686716/154431422-c0918743-efb5-482f-92a7-cd46494061a0.png)

cc @matikrk

**Comment by coderitual** [comment]
Thank you @wasilakkf for reporting this. We will resolve this issue soon.

**Comment by coderitual** [comment]
Fixed. Closing.
