### ISSUE TITLE
Translations - OneSky

### ISSUE THREAD

**Issue by JanuszSzewczyk** [brainly/style-guide#235]
My idea is to change source strings in code to ID's because all sentences in OneSky have own unique id.
It will be easier to find, change, add new translations.
![pasted image at 2015_09_01 05_07 pm](https://cloud.githubusercontent.com/assets/13464120/9608153/43dd17f4-50cd-11e5-80e2-b17f8a9efc07.png)

**Comment by vergilius** [comment]
See discussion: https://github.com/brainly/web-client/issues/182

**Comment by kdzwinel** [comment]
Shell we close this? Relevant discussion is already happening in https://github.com/brainly/web-client/issues/182 .

**Comment by kdzwinel** [comment]
invalid
