### ISSUE TITLE
Opera Mini: select reloads the page

### ISSUE THREAD

**Issue by kdzwinel** [brainly/style-guide#236]
<img width="446" alt="screen shot 2015-09-01 at 14 55 05" src="https://cloud.githubusercontent.com/assets/985504/9609170/7c84cae8-50d2-11e5-879f-a586e419e71f.png">

Both selects pictured above reload page on click. This makes it impossible to use them.

I spent some time tracking down this bug and it turns out that these styles cause that issue:

     cursor: pointer;
     border: none;

So the question is, should we:
- remove one of these properties,
- set border to `solid 1px transparent` (it works, I checked) or
- do something else?

cc @mr-mig @matzimowski WDYT?

**Comment by kdzwinel** [comment]
Turns out it's a feature of Opera Mini: http://stackoverflow.com/a/32381403/1143495 . Anyway, we still have to resolve it somehow.

**Comment by mr-mig** [comment]
We need to remove the cursor. And maybe add this info in the README guidelines

**Comment by kdzwinel** [comment]
Closed via #280
