### ISSUE TITLE
text-bit--large?

### ISSUE THREAD

**Issue by kdzwinel** [brainly/style-guide#241]
http://brainly.com/login page uses two undocumented size versions of text-bit with font-size 72px and 80px . IMO we should ditch one of these and add the second one to the styleguide.

@aju WDYT?

<img width="889" alt="screen shot 2015-09-02 at 16 00 39" src="https://cloud.githubusercontent.com/assets/985504/9633216/ef841cba-518b-11e5-86cd-ad587c7259b4.png">

**Comment by aju** [comment]
@kdzwinel yeah good idea - issue is this text bits are responsive (changing font-size on desktop)

**Comment by mr-mig** [comment]
Keep in mind that I am changing the texts.
There is no such thing as a large text-bit yet.
