### ISSUE TITLE
What benefits do we get by not referencing variables directly in components?

### ISSUE THREAD

**Issue by mr-mig** [brainly/style-guide#244]
Why do we do `myComponentFontFamily: $fontFamilyPrimary`?

**Comment by aju** [comment]
Font family might be bad example as I wrote in other ticket we should make it global.
Other than that referencing for example colours and is really cool and make it easy to refactor components (you can see all important setting for component in one place)

**Comment by mr-mig** [comment]
For me, the mental burden for finding `color: $white` is much less than adding a variable for each changeable parameter

**Comment by vergilius** [comment]
This works fine (referencing variables directly from config), until you have to put it in 2 or more places.
Imho we should stick to having additional variables as it allows to easilly see what config variables, colors are used in component.

**Comment by kdzwinel** [comment]
I agree with Michal, these variables give a quick overview of the color palette used by the component + they clearly state that "the same color should be used in these two (or more) places".

**Comment by aju** [comment]
@mr-mig can we keep then this convention and close this issue?:) (We can see in some time if we still agree on this in the future)

**Comment by mr-mig** [comment]
So, summing up:

1. Gives the overview for all **changeable parameters** for a given components
1. Allows easily **reuse** the variable
1. Allows **referencing** parameters of other components
1. Makes refactoring easier

**Comment by aju** [comment]
@mr-mig maybe its a good idea to put this in documents to explain why we do it that way?

**Comment by mr-mig** [comment]
@aju its in Contributing PR #273

**Comment by aju** [comment]
thx!
