### ISSUE TITLE
Why we reference specific attributes in every component instead of inheriting?

### ISSUE THREAD

**Issue by mr-mig** [brainly/style-guide#245]
We refer to `$fontFamilyPrimary` in every component, but it can be a part of `<body>`, e.g. default text font-family.

The same goes for text sizes and line-height.

What are the benefits?

**Comment by mr-mig** [comment]
This approach makes sense when you do not know how your things will be generalized and where the commonality lies.
It creates a self-scoped components with guarantees that no simple change to global values can break them.

Shall we continue with this approach?
Shall we refactor the things, when we see that something can be generalized?

**Comment by aju** [comment]
+1 for generalising things like font-family, line-height, font-size

**Comment by matzimowski** [comment]
Try to put content box inside content-box--spaced.
It inherits the padding from content-box--spaced, which is obviously the incorrect  behaviour.
Adding all the styles explicitly (like `padding: 0`) will prevent us from having this issue.

**Comment by aju** [comment]
@mr-mig as font is inherited do you see any other things that should be inherited?

**Comment by mr-mig** [comment]
I always hesitate between specifying everything explicitly in the components and not specifying some things. 

The font is inherited cause it depends implicitly on the root font.

I do not have a good strategy to deal with that. 

I still thing I'd prefer to have default font and line-height specified in `component` mixin (and a bunch of other mixins), so that we can create components/containers like that: 

```
.mint-something {
  @include component, singleLineComponent, roundedBorders;
  @include container, holes;
  @include mintTheme;
}

```
