### ISSUE TITLE
User panel

### ISSUE THREAD

**Issue by matzimowski** [brainly/style-guide#246]
Consider adding an user panel from symfony to the style-guide.
imho, only one thing that is worth to add is this blue container with triangle at the top.

<img width="504" alt="screen shot 2015-09-03 at 13 33 25" src="https://cloud.githubusercontent.com/assets/1231144/9659097/82b01260-524e-11e5-918a-b6619c9bb73e.png">
<img width="507" alt="screen shot 2015-09-03 at 13 50 35" src="https://cloud.githubusercontent.com/assets/1231144/9659096/82adc03c-524e-11e5-8ec9-68ad1e96ca91.png">

**Comment by mr-mig** [comment]
Blue container + holes inside

**Comment by matzimowski** [comment]
:+1: makes sense
