### ISSUE TITLE
Move stream container to styleguide

### ISSUE THREAD

**Issue by vergilius** [brainly/style-guide#250]
Lets create container for stream with questions

Related: https://github.com/brainly/style-guide/issues/251

**Comment by kdzwinel** [comment]
This thing?

<img width="341" alt="screen shot 2015-09-04 at 17 00 03" src="https://cloud.githubusercontent.com/assets/985504/9686883/6c6392ec-5326-11e5-8222-dc507a4f9b0c.png">

**Comment by vergilius** [comment]
I believe the whole component should also have buttons from top and bottom.

**Comment by mr-mig** [comment]
It should be a container with holes for content-box. Separator should go away and rest in peace.

**Comment by vergilius** [comment]
Let's move it to common-web-bundle, also, the stream question element is combination of existing components (see content-box).
