### ISSUE TITLE
URL providing to the story on the latest version of style guide

### ISSUE THREAD

**Issue by coderitual** [brainly/style-guide#2511]
Currently to link to particular story in storybook we need to include version of the styleguide within url, e.g:

![CleanShot 2022-08-17 at 10 01 37](https://user-images.githubusercontent.com/8572321/185066689-2ec446f9-3b90-4b8b-be91-8a711a017a65.png)

[https://styleguide.brainly.com/**218.0.1**/docs/?path=/story/components-dialog--default-story](https://styleguide.brainly.com/218.0.1/docs/?path=/story/components-dialog--default-story)

The ideal solution would be to provide a link leading to a specific component without worrying about the version e.g:

[https://styleguide.brainly.com/?path=/story/components-dialog--default-story](https://styleguide.brainly.com/?path=/story/components-dialog--default-story)

_(above link of course is not working as expected, redirecting as to the latest homepage)_

**Comment by clxandstuff** [comment]
fixed in https://github.com/brainly/style-guide/pull/2514
