### ISSUE TITLE
Standarize vocabulary

### ISSUE THREAD

**Issue by kdzwinel** [brainly/style-guide#252]
Look at modifiers for different components:
- `--big`
- `--huge`
- `--large`

Lets standarize that (and all other similar cases).

**Comment by aju** [comment]
As we talked today we always should start with elements that are used on mobile and scale them up automatically if needed on tablet/desktop view. To follow this we should use modifiers to upscale elements and we should come up with some consistent names for it. (large larger largest?:) )

**Comment by vergilius** [comment]
I've checked different modifiers and I've put them into categories. There are also names connected with types (mostly buttons), but I've skipped them here.

Sizes:
- `small`,
- `medium`,
- `big`,
- `low` (hell yeah ;P),
- `large`,

and also (widths):
- `full` (block in bootstrap),
- `spaced`,
- `side-spaced`

Transformations:
- `emphasized`,
- `upper`

Status:
- `inactive`,
- `disabled`

For these categories I suggest:
- take sizes from bootstrap: `extra-small`, `small`, `large`, `extra-large`,
- remove all references to `default`, `medium` modifiers and apply them to block/element by default,
- change to `emphasized` from `upper`,
- keep `inactive` due to `active` usages and remove `disabled`


Also, we've discussed with @kdzwinel and @aju about directions of paddings inside components (for example `box` or `bubble`), we suggest to have default padding/margin in parent component, and every other changes to be applied from child component.

**Comment by matzimowski** [comment]
:+1: i am fine with your propositions.
:dolls:

**Comment by kdzwinel** [comment]
I kinda liked 'low'... :cry: 

Anyway, yeah, I like this proposal :+1:

**Comment by mr-mig** [comment]
> put them into categories

There are 4 typical categories:

* 1D - width/height, (`narrow`, `wide`, `tall`, `short`)
* 2D - box sizes (`small`, `medium`, `large`), often relates to the responsive behavior or scale factor.
* 3D - box sizes + depth, or only depth. Applicable to font-sizes (`emphasized`, `obscured`, `hero`, `standout`)
* Contrast - `inverse`, `standout`, `call-to-action`, `call-out`

Also note:

* `disabled` and `inactive` are different.
* `medium` and `default` can be different as well.

> we suggest to have default padding/margin in parent component, and every other changes to be applied from child component.

Does not work all the time, unfortunately :(

**Comment by mr-mig** [comment]
I'd propose to reason about semantics like that:

* The name should hint you how it is intended to be used (**intent**)
* The name should describe how the element will be modified without ambiguities (large - is it only width, or is it only font?) (**meaningful**)

**Comment by mr-mig** [comment]
2D-sizes famuily can have names like `xs`, `s`, `m`, `l`, `xl`

**Comment by mr-mig** [comment]
Also, do not mix in the **responsiveness** with modifier axes.
Responsiveness is built-in, it is there by default, and it is one fixed axis we always take into account.

**Comment by mr-mig** [comment]
I would suggest to figure out what **axes** and **behavior changes** we have and categorize them first.
And then come up with the modifier names.

**Comment by vergilius** [comment]
> disabled and inactive are different.

Its up to us how do we treat them. I personally do not see difference between `disabled` and `inactive`, and no one here could explain it to me clearly, could you do it please?

> medium and default can be different as well.

Also, I wanted to say that we should have `default` size for components, that do need other modifiers, but problem here is we do not know what this size should be (I thought that all components by default are `medium`)

> I would suggest to figure out what axes and behavior changes we have and categorize them first.

IMHO its connected to the thing above, agreed

> 2D-sizes famuily can have names like xs, s, m, l, xl

Agreed, thats 1:1 how bootstrap deals with this

**Comment by mr-mig** [comment]
> and no one here could explain it to me clearly, could you do it please?

`Disabled` - user is unavailable to interact with the element at all. Disabled dropdown - you cannot do anything with it at all.

`Inactive` - user did not interacted with the element yet. It will become `active` as soon as user will do smth with dropdown. `Active` is a more general version of `hover`  or `pressed`, for example. 

> I thought that all components by default are `medium`

This is what we need to decide **explicitly**.

**Comment by vergilius** [comment]
> difference between `disabled` and `inactive`

Ok, so `disabled` means that state cannot be changed? and this is more connected to attribute, so probably should be managed through JS?

**Comment by mr-mig** [comment]
We have discussed the issue on the meeting and have decided to have this convention:

- 1D:
  `xnarrow`
  `narrow`
  `wide`
  `xwide`
  `full-width`

  `xshort`
 `short`
  `tall`
  `xtall`
  `full-height`

2D:
  `xsmall`
  `small`
  `large`
  `xlarge`

Behavior:
 - `non-responsive`
 - `obscured`
 - `standout`
 - `disabled`
 - `active`/`inactive`

Combinations:
 - `padding-wide`
 - `padding-tall`
 - `paddind-large`

**Comment by kdzwinel** [comment]
This is closed, isn't it? https://github.com/brainly/style-guide/blob/master/CONTRIBUTING.md#modifier-dictionary
