### ISSUE TITLE
Add mint-badge mustard modificator

### ISSUE THREAD

**Issue by vergilius** [brainly/style-guide#253]
![screen shot 2015-09-04 at 17 15 58](https://cloud.githubusercontent.com/assets/1142999/9687308/072f4f12-5329-11e5-9108-25e2d80d2f3c.png)

**Comment by kszychooo** [comment]
@vergilius I'm pretty sure, that the copy should be capitalize :)

**Comment by vergilius** [comment]
that's just content ;P
