### ISSUE TITLE
Rounded top corners for dialog fullscreen mobile

### ISSUE THREAD

**Issue by lewandowskid** [brainly/style-guide#2566]
![Screenshot 2022-10-24 at 17 32 42](https://user-images.githubusercontent.com/53941885/197565900-c96d82fb-72f9-4103-9268-21059e004b73.png)

I don't know why, but the top corners in dialog fullscreen on mobile have `border-radius: 8px;` and should have `0px;`

It was working correctly in 219.0.0
https://styleguide.brainly.com/219.0.0/docs/?path=/story/components-dialog--default-story&args=size:fullscreen

and now it's not right:
https://styleguide.brainly.com/220.3.0/docs/?path=/story/components-dialog--default-story&args=size:fullscreen

**Comment by coderitual** [comment]
thanks for reporting @lewandowskid

**Comment by lewandowskid** [comment]
fixed by this pr
https://github.com/brainly/style-guide/pull/2583
