### ISSUE TITLE
Allow Flex component to receive gap property

### ISSUE THREAD

**Issue by azajac-brl** [brainly/style-guide#2574]
**Problem:**
Often I find myself in situation where I need to add `className` to `Flex` component only to be able to specify `gap` property. Because of that i need to create artificial classes only for this reason.

**Proposed solution:**
Ideally I'd like `Flex` to accept `gap` property with values being SG sizes, for example `<Flex  gap="m" />`

**Comment by coderitual** [comment]
sounds like a good idea, until it's implemented you can use utility clasess to achieve the same effect, e.g:

`<Flex className="sg-space-x-s">`
