### ISSUE TITLE
Max-width in all input elements

### ISSUE THREAD

**Issue by coderitual** [brainly/style-guide#2591]
Based on PR: https://github.com/brainly/style-guide/pull/2590

input elements contain following attribute:
`max-width: min-content` 

which seems not doing anything useful and maybe it's even wrong. In some scenarios this attribute is responsible for excessively narrowing input control:

![CleanShot 2022-11-30 at 10 12 59](https://user-images.githubusercontent.com/8572321/204755487-c42abb4b-1108-4bc7-b4b3-e9ce74597e8c.png)

**Comment by clxandstuff** [comment]
@coderitual 
This CSS rule was added to fix a long error message, making an input too wide. This is original PR https://github.com/brainly/style-guide/pull/1797. 

We can replace this rule by adding a default fixed width to the input, but I think it works as expected. Do you remember what caused the issue on the screenshot?
