### ISSUE TITLE
Add box-sizing:border-box to basics

### ISSUE THREAD

**Issue by matzimowski** [brainly/style-guide#260]
Add box-sizing:border-box into basic styles for * elements.
wdyt @mr-mig @aju @vergilius @kdzwinel

**Comment by kdzwinel** [comment]
I'm even OK with `*{box-sizing:border-box}`

**Comment by aju** [comment]
I prefer border-box so either solution is ok with me. Its already added to "component" mixin maybe we should use it more often?

**Comment by matzimowski** [comment]
i thought about @kdzwinel solution with `*` if we use it in probably all cases.

**Comment by mr-mig** [comment]
I have the same inquiry regarding the font-family and default line-height.
I have already added them to the `body` tag, but I always worry about global solutions.

But, as we have versions in styleguide - we are free to experiment.
I would say - lets add `border-box` to all elements and see what happens :)
