### ISSUE TITLE
Radio component has wrong type for onChange property

### ISSUE THREAD

**Issue by coderitual** [brainly/style-guide#2602]
Screenshot below is coming from the frontend app where type is already converted from Flow to typescript. 

![CleanShot 2022-12-12 at 12 53 09](https://user-images.githubusercontent.com/8572321/207038672-a16d6c37-5d22-44e3-b40c-672ddc575e1e.png)

Plausible solution: use the same type as in checkbox

**Comment by katarzynatobis** [comment]
Fixed in #2604
