### ISSUE TITLE
Select input seems to have incorrect chevron icon position

### ISSUE THREAD

**Issue by coderitual** [brainly/style-guide#2607]
![CleanShot 2022-12-14 at 12 19 03](https://user-images.githubusercontent.com/8572321/207581995-f846bec8-00c2-43cf-892f-d92810e6838a.png)

Also during rerender there is another arrow coming out from layout (to be verified)
![CleanShot 2022-12-14 at 12 20 02](https://user-images.githubusercontent.com/8572321/207582151-a66e867e-842c-4973-a95f-32a4fe9e86d1.gif)

**Comment by clxandstuff** [comment]
Tested on prod, looks good.

https://user-images.githubusercontent.com/25419830/225074682-c7195142-e5bd-4fea-a682-73159da33fc9.mov
