### ISSUE TITLE
Wrong names of subject icons

### ISSUE THREAD

**Issue by matzimowski** [brainly/style-guide#261]
i.ex.
`mathematics` should be `maths` and so on.

these names come from API, we should use them even if they are not the best ones.

**Comment by aju** [comment]
I think mapping icons is better idea. See how its handled in symfony.

**Comment by matzimowski** [comment]
@aju suggested to move it into the style-guide, right now it's implemented is symfony like:
`
.mint-subject-icon--technology-electronics {
  &:extend(.mint-subject-icon--technology);
}

.mint-subject-icon--all {
  &:extend(.mint-subject-icon--wos);
}

.mint-subject-icon--greek {
  &:extend(.mint-subject-icon--otherlanguages);
}

.mint-subject-icon--polish,
.mint-subject-icon--russian-lit{
  &:extend(.mint-subject-icon--literature);
}

.mint-subject-icon--po {
  &:extend(.mint-subject-icon--health);
}

.mint-subject-icon--technique,
.mint-subject-icon--tec {
  &:extend(.mint-subject-icon--skills);
}

.mint-subject-icon--other-lang,
.mint-subject-icon--others{
  &:extend(.mint-subject-icon--otherlanguages);
}

.mint-subject-icon--enterprise {
  &:extend(.mint-subject-icon--business);
}

.mint-subject-icon--math {
  &:extend(.mint-subject-icon--mathematics);
}

.mint-subject-icon--deutsch {
  &:extend(.mint-subject-icon--german);
}

.mint-subject-icon--euskera {
  &:extend(.mint-subject-icon--euskara);
}

.mint-subject-icon--it {
  &:extend(.mint-subject-icon--informatics);
}

.mint-subject-icon--port {
  &:extend(.mint-subject-icon--literature);
}

.mint-subject-icon--sosyal{
  &:extend(.mint-subject-icon--social);
}

.mint-subject-icon--geol {
  &:extend(.mint-subject-icon--geology);
}

.mint-subject-icon--belarusian {
  &:extend(.mint-subject-icon--belarus);
}

.mint-subject-icon--kazakh {
  &:extend(.mint-subject-icon--kazach);
}

.mint-subject-icon--ukrain-lit {
  &:extend(.mint-subject-icon--literature);
}

.mint-subject-icon--art-music {
  &:extend(.mint-subject-icon--artmusic);
}

.mint-subject-icon--home-economics {
  &:extend(.mint-subject-icon--others);
}

.mint-subject-icon--india-lang {
  &:extend(.mint-subject-icon--otherlanguages);
}

.mint-subject-icon--indonesian-lang {
  &:extend(.mint-subject-icon--otherlanguages);
}

.mint-subject-icon--nigerian-lang {
  &:extend(.mint-subject-icon--otherlanguages);
}
.mint-subject-icon--norwegian {
  &:extend(.mint-subject-icon--otherlanguages);
}
.mint-subject-icon--rpa-lang {
  &:extend(.mint-subject-icon--otherlanguages);
}

.mint-subject-icon--tamil {
  &:extend(.mint-subject-icon--otherlanguages);
}

.mint-subject-icon--dkab {
  &:extend(.mint-subject-icon--religion);
}

.mint-subject-icon--mantik {
  &:extend(.mint-subject-icon--logic);
}

.mint-subject-icon--matury {
  &:extend(.mint-subject-icon--egzam);
}

.mint-subject-icon--policy {
  &:extend(.mint-subject-icon--politics);
}

.mint-subject-icon--saglik {
  &:extend(.mint-subject-icon--health);
}

.mint-subject-icon--traffic {
  &:extend(.mint-subject-icon--trafic);
}

.mint-subject-icon--other-subjects {
  &:extend(.mint-subject-icon--others);
}

.mint-subject-icon--accounting {
  &:extend(.mint-subject-icon--statistics);
}

.mint-subject-icon--administracao {
  &:extend(.mint-subject-icon--administration);
}
`

and we probably do not want to`@extend` it in sass like this.
