### ISSUE TITLE
Allow Box component to have no children - static type checking

### ISSUE THREAD

**Issue by matzimowski** [brainly/style-guide#2625]
Currently it throws an error:

<img width="703" alt="Screenshot 2023-01-04 at 10 35 16" src="https://user-images.githubusercontent.com/1231144/210525651-2ef68596-a70c-4157-9c0c-1009e83e3cd0.png">

## use case: (skeleton placeholder)

![box-placeholder](https://user-images.githubusercontent.com/1231144/210525561-5e519e37-375b-4bac-b82e-7081ec61d772.png)

**Comment by coderitual** [comment]
Will be fixed in https://github.com/brainly/style-guide/pull/2628

**Comment by katarzynatobis** [comment]
Fixed in #2628
