### ISSUE TITLE
Search component's button unmounts unexpectedly 

### ISSUE THREAD

**Issue by przytrzask** [brainly/style-guide#2713]
## Problem
In a search component we have following conditional rendering 
```ts
{withRoundButton ? (
        <div className={`${baseClassName}__icon`}>
          <Button
            variant="solid"
            className={cx({
              'sg-search-button--s': size === 's',
            })}
            icon={
              <Icon
                type="search"
                size={size === 'l' ? 24 : 16}
                color="adaptive"
              />
            }
            iconOnly
            size={size === 'l' ? 'm' : 's'}
          />
        </div>
      ) : (
        <button className={`${baseClassName}__icon`}>
          <Icon
            type="search"
            color={ICON_COLOR['icon-gray-50']}
            size={size === 'l' ? 24 : 16}
          />
        </button>
      )}
```

and since we use this component based on whether it is focused or not like this 
```ts
turn (
    <Search
      withRoundButton={focused}
```

then because blur happens first, the button unmounts next submit is never called

![CleanShot 2023-04-03 at 09 25 40](https://user-images.githubusercontent.com/20127089/229440680-76bdbf97-bf36-437a-954b-35d7587ebc8b.gif)

### Proposed solution

I think it will be rather easy to style this button using classes only instead of conditional rendering

**Comment by coderitual** [comment]
Hey @przytrzask , feel free to use pseudo elements / switchable wrappers to avoid conditional rendering and keep things on css level only.

**Comment by katarzynatobis** [comment]
@przytrzask is this issue in progress or can I take it over?
