### ISSUE TITLE
Automatic deploy

### ISSUE THREAD

**Issue by kdzwinel** [brainly/style-guide#279]
We need to figure out how to automatically deploy stuff whenever new tag is pushed to master.

**Comment by mr-mig** [comment]
Push Alaa. We need a reverse proxy for Jenkins. 
It is in the list, the priority is quite low.

We can try find someone who can help set it up.

**Comment by kdzwinel** [comment]
Thanks for a tip! @alaa can you help us with that?

**Comment by kdzwinel** [comment]
Talked with @winglot, he advised us to use this setting in jenkins:

<img width="417" alt="screen shot 2015-09-11 at 15 56 52" src="https://cloud.githubusercontent.com/assets/985504/9816530/d948b3d4-589d-11e5-9287-3d0f00c7f5a2.png">

Apparently we don't need a reverse proxy?

**Comment by mr-mig** [comment]
Polling SCM will kill the jenkins box when there will be several build (docker + frontend). It's a coslty operation.

**Comment by aju** [comment]
We have automatic deployment after merging to master.
