### ISSUE TITLE
Use React Context API for detecting nested components, ie. in Dialog component

### ISSUE THREAD

**Issue by matzimowski** [brainly/style-guide#2795]
instead of accessing DOM to find nested components, ie:
```
const isNestedDialog = overlayRef.current?.parentElement?.closest(DIALOG_SELECTOR);
```
use React Context API

good read: https://www.aleksandrhovhannisyan.com/blog/react-context-nested-components/

**Comment by Malinicz** [comment]
Closing due to fix that doesn't require context usage, ref: https://github.com/brainly/style-guide/pull/2821
