### ISSUE TITLE
Check which dot should be used in breadcrumbs

### ISSUE THREAD

**Issue by kdzwinel** [brainly/style-guide#282]
content: '·';

vs

        content: '•';

<img width="432" alt="screen shot 2015-09-14 at 15 26 45" src="https://cloud.githubusercontent.com/assets/985504/9850809/5cf2c00e-5af5-11e5-848a-ba1e4af12a4d.png">

**Comment by JoannaWalusiak** [comment]
Set the smaller one  '·'  :)
