### ISSUE TITLE
Investigate preconnect

### ISSUE THREAD

**Issue by mr-mig** [brainly/style-guide#292]
This thing may reduce loading time for all projects using style-guide:
https://www.igvita.com/2015/08/17/eliminating-roundtrips-with-preconnect/

**Comment by kdzwinel** [comment]
But we serve everything from the same domain (styleguide.brainly.com) don't we? As far as I understand preeconnect helps in cases like the one described where google font stylesheet is loaded from `fonts.googleapis.com` but fonts are served from `fonts.googleapis.com`.

**Comment by mr-mig** [comment]
Yeah, maybe then `prefetch` can be used?

**Comment by aju** [comment]
I don't think its needed as we reference styleguide in <head> and use it directly (we are not embedding it from JS for example)

**Comment by mr-mig** [comment]
Well, we are not embedding it with JS **yet** (it may be the case for above-the-fold in the future)

**Comment by aju** [comment]
I think that we should not optimise prematurely

**Comment by mr-mig** [comment]
How do you define `prematurely`?

**Comment by aju** [comment]
We don't need it now - and we are not going to need it in short future (there is no issue connected with it)

**Comment by mr-mig** [comment]
There is no issues because no one is interested in it yet (as it was with VR, for example).

Why don't we need it?

**Comment by aju** [comment]
Do you see any case where it would make our page faster?

**Comment by mr-mig** [comment]
Anywhere, where styleguide will be used in a real website. As soon as you have `style-guide.brainly.com` domain in styles and any specific styles from local domain.

Either the styleguide, or the local domain can be "preconnected" while the first batch of styles are downloaded

**Comment by aju** [comment]
Im not sure - we need to test this use case as both "domains are in HTML". If this will help then we should use it.

**Comment by aju** [comment]
BTW: https://css-tricks.com/prefetching-preloading-prebrowsing/

**Comment by mr-mig** [comment]
But the whole point of this issue is to investigate whether this will help or not. I do not see how investigation can be a premature optimization (I hate this principle in general, as it is very vague)

**Comment by aju** [comment]
Ok lets test it our selfs.

**Comment by mr-mig** [comment]
Having this issue does not mean we need to do it ASAP. 
It's just a documented inquiry to check it some time, as I will definitely forget about that.

**Comment by aju** [comment]
And just to clarify about premature optimisation I was talking about the
part that maybe we will load it with js(and that we should not optimise for
maybe cases). Other than that I agree lets check those methods if they will
speed up the page.

**Comment by matzimowski** [comment]
update:
we have added dns-prefetch: https://github.com/brainly/web-client/pull/1737

**Comment by aju** [comment]
Im closing this one -> its more wc/syfmfony related

**Comment by matzimowski** [comment]
and then switched to preconnect: https://github.com/brainly/common-web-bundle/releases/tag/0.70.0
