### ISSUE TITLE
Add mint-breakpoint mixin

### ISSUE THREAD

**Issue by aju** [brainly/style-guide#294]
Should work like:
`@include mint-breakpoint(tablet-only)` === `@media (min-width: $breakpointMedium) and (max-width: $breakpointLarge - 1px)`

**Comment by aju** [comment]
@mr-mig its similar concept to: http://www.zell-weekeat.com/mappy-breakpoints/ but simpler and using names from foundation

**Comment by mr-mig** [comment]
Yeah, makes sense for me

**Comment by matzimowski** [comment]
:+1:

**Comment by vergilius** [comment]
yep :+1:
