### ISSUE TITLE
Figure out a better way of triggering the rhythm guidelines

### ISSUE THREAD

**Issue by mr-mig** [brainly/style-guide#303]
The current implementation messes up all pointer events (scroll, clicks, hovers).

It may be solved as a checkbox, which triggers all guidelines in the document.

**Comment by aju** [comment]
@mr-mig is current solution good enough? (checkbox on navigation)

**Comment by mr-mig** [comment]
It can be updated to that checkboxes trigger the guidelines and holes so that you do not need to hover over the elements. 
Anyway, its ok. Closing.
