### ISSUE TITLE
Fix line wrapping in mint-list

### ISSUE THREAD

**Issue by mr-mig** [brainly/style-guide#315]
In this image the fitst line should be wrapped so that text lines are lined-up from the left:
![](https://i.gyazo.com/c19787aac445d3bec21a363aed21c922.png)

**Comment by matzimowski** [comment]
it works well already:
<img width="334" alt="screen shot 2016-06-15 at 15 40 40" src="https://cloud.githubusercontent.com/assets/1231144/16081843/95dd8190-330f-11e6-97a7-8c6073f9d442.png">


i am closing this issue.
