### ISSUE TITLE
Site grid - cleaning

### ISSUE THREAD

**Issue by JanuszSzewczyk** [brainly/style-guide#350]
Update:
aside-content column in fixed width

24 + 600 + 48 + 288 + 24 = 984 II column
24 + 480 + 48 + 288 + 24 = 864 II column
if < 863 I column
24 + 600 + 24 = 648 max width of main column 
if >768 then it should be centered?
24 + 272 + 24 = 320 min. width

**Comment by JoannaWalusiak** [comment]
Update:
aside-content column in fixed width 

24 + 600 + 40 (24+16) + 272 + 24 = 960  II column
24 + 480 + 40 + 272 + 24 = 840  II column
if < 839  I column
24 + 600 + 24 = 648 max width of main column 
if >768 then it should be centered?
24 + 272 + 24 = 320 min. width

**Comment by matzimowski** [comment]
we have added the layout component http://styleguide.brainly.com/41.0.1/docs/containers.html#layout
is it a time to close the issue? @aju @vergilius @kdzwinel

**Comment by aju** [comment]
yes, lets close it
