### ISSUE TITLE
Figure out how to stop content-box abuse (grid? cols+rows? something else?)

### ISSUE THREAD

**Issue by kdzwinel** [brainly/style-guide#365]
https://github.com/brainly/style-guide/pull/341#issuecomment-143259747

**Comment by vergilius** [comment]
I'd propose to use content-box as a mixin, could be used in places where we use it already, but would require us to create less generic components (i.e mint-ranking, mint-panel etc)

**Comment by mr-mig** [comment]
I'd propose to create one specific conteiner called `mint-media`.
Have a look: http://www.stubbornella.org/content/2010/06/25/the-media-object-saves-hundreds-of-lines-of-code/

It's already baked in `content-box`, so we can ditch it out (or use content-box only as media)

One more step is to create a separate component-containers for *typed holes* for `title`, `content` and `actions`

**Comment by kdzwinel** [comment]
as mentioned on slack:

> 
as for the ‘media object’ it absolutely does look like ‘content-box’ :simple_smile: Still, all the usecases that they present for their ‘media object’ seem reasonable and semantic. ‘content-box’ is being used in various context where it doesn’t seem to fit. Yet again though - it might be just a matter of naming.

**Comment by mr-mig** [comment]
Shall we call `content-box` -> `mint-block`  ?

**Comment by vergilius** [comment]
we have decided to stick to content-box and actions-list for now, cc @aju
