### ISSUE TITLE
Overriding properties of the same selector

### ISSUE THREAD

**Issue by aju** [brainly/style-guide#386]
We have constructs like:
https://github.com/brainly/style-guide/blob/master/src/components/badges/_badges.scss#L13
So both mixins are setting same properties like `line-height` this is a bit confusing and we have to override them later. In addition it produces code like this:
```
.mint-badge {
    display: inline-block;
    position: relative;
    overflow: hidden;
    text-overflow: ellipsis;
    line-height: 1.5rem;
    min-height: 1.5rem;
    margin: 0;
    font-size: 0.625rem;
    height: 0.625rem;
    line-height: 0.625rem;
    text-transform: uppercase;
    letter-spacing: 0.03rem;
    overflow: visible;
    min-height: auto;
    height: auto;
    border-radius: 0.625rem;
    font-weight: 700;
    padding: 3px 6px;
    background-color: #fff;
    color: #000;
}
```
I think we should fix it.

I will add plugin for removing such duplication from generated css files. Do you think its enough?
Maybe we should change those mixing to look more like:
```
@mixin component($lineHeight: rhythm(1), $overflow: hidden) {
  display: inline-block;
  position: relative;
  overflow: $overflow;
  text-overflow: ellipsis;
  line-height: $lineHeight;
  min-height: rhythm(1);
  margin: 0;
}
```
Then we wouldn't have to do thing like that:
```
  .mint-badge {
    @include component;
    @include fixText($badgeFontSize);
    @include uppercaseText;
    overflow: visible; // allow badges align as text
    min-height: 0;
    height: auto;
```

WDYT?
@mr-mig @vergilius @kdzwinel @matzimowski

**Comment by mr-mig** [comment]
I'd prefer to have semantic mixins, like `inlineComponent`, etc.

Line-height is overriden for a reason. Simle rule `line-height: 1` does not mean anything and show no reason.

I believe this is the SRP violation in component mixin. 
See also #301
