### ISSUE TITLE
Fix mint-popup-menu to follow VR

### ISSUE THREAD

**Issue by aju** [brainly/style-guide#424]
<img width="371" alt="screen shot 2015-10-09 at 14 04 07" src="https://cloud.githubusercontent.com/assets/316313/10393274/c4ddd21a-6e8e-11e5-9d2e-71aa3151827b.png">
Example has 56px and there is no simple option to force it to follow vertical rhythm.

**Comment by mr-mig** [comment]
The question is: do we need it to follow VR at all? 
This thing is always on the top z-layer...

**Comment by aju** [comment]
Will leave it as it is
