### ISSUE TITLE
Add '.mint-header-secondary--v-centered'

### ISSUE THREAD

**Issue by aju** [brainly/style-guide#429]
```
.mint-header-secondary--v-centered {
  display: flex;
  align-items: center;
}
```

**Comment by kdzwinel** [comment]
or.... `min-height: initial` ?

**Comment by mr-mig** [comment]
How do you determine that the text is not wrapped in the secondary header?

**Comment by aju** [comment]
Then its fine take a look at screenshots:
<img width="541" alt="screen shot 2015-11-09 at 08 45 55" src="https://cloud.githubusercontent.com/assets/316313/11028382/73d53b36-86be-11e5-975a-310fe9a5b7a1.png">
<img width="609" alt="screen shot 2015-11-09 at 08 46 28" src="https://cloud.githubusercontent.com/assets/316313/11028381/73d4d0ba-86be-11e5-8cfa-bbe9826f9a9b.png">

**Comment by aju** [comment]
This is invalid.
