### ISSUE TITLE
Move mint-media to styleguide from symfony

### ISSUE THREAD

**Issue by vergilius** [brainly/style-guide#431]
![screen shot 2015-10-13 at 11 37 23](https://cloud.githubusercontent.com/assets/1142999/10451166/d6a01496-719e-11e5-8d4d-94e91b33022b.png)

**Comment by mr-mig** [comment]
@vergilius  Is it the same as #250 ?

**Comment by vergilius** [comment]
nope, its single component from list above wrapped in list, we just need media (avatar + content on right)
