### ISSUE TITLE
max-width: 100% for mint-primary-header

### ISSUE THREAD

**Issue by matzimowski** [brainly/style-guide#459]
It allows header to wrap on ie10.
```
.mint-header-primary {
  max-width: 100%;
}
```

before:
<img width="981" alt="screen shot 2015-10-22 at 11 57 52" src="https://cloud.githubusercontent.com/assets/1231144/10662350/3c606b0c-78b4-11e5-95b4-5996b461b3b3.png">

after:
<img width="977" alt="screen shot 2015-10-22 at 11 58 00" src="https://cloud.githubusercontent.com/assets/1231144/10662356/4559456c-78b4-11e5-9387-d0e724686f7c.png">

**Comment by mr-mig** [comment]
See https://github.com/philipwalton/flexbugs#workaround-1 for details
