### ISSUE TITLE
Fixing min-height for content-box for ie10-11

### ISSUE THREAD

**Issue by matzimowski** [brainly/style-guide#462]
<img width="314" alt="screen shot 2015-10-22 at 12 18 32" src="https://cloud.githubusercontent.com/assets/1231144/10662775/13743360-78b7-11e5-8bc4-6680b707dcf8.png">

more info:
https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items

**Comment by vergilius** [comment]
check if it's still applicable (remember about browser support), @matzimowski

**Comment by kdzwinel** [comment]
We no longer officially support IE10-11
