### ISSUE TITLE
[IE Edge] flexbox + align-items: center + height:100% on a child element. 

### ISSUE THREAD

**Issue by matzimowski** [brainly/style-guide#463]
Investigate the issues with flexbox + align-items: center + height:100% on a child element. 

There is a problem of parent container growing when the sibling is removed from the flex layout context in IE Edge.

It can be reproduced with `mint-ranking` component + `mint-floating-box` on Main Page. You need to apply `height:100%` to the `.mint-ranking .mint-box__hole` and scroll the page to see the effects.

<img width="356" alt="screen shot 2015-10-22 at 13 04 54" src="https://cloud.githubusercontent.com/assets/1231144/10663687/92bb36ae-78bd-11e5-8608-0abc1ef106b1.png">

It would be cool to be able to reproduce it on jsfiddle and report to https://github.com/philipwalton/flexbugs

**Comment by coderitual** [comment]
@matzimowski I am closing it due to long inactivity. Please let me know if we need to reopen :)
