### ISSUE TITLE
[IE] flexbox + flex-basis: 100% on a child element.

### ISSUE THREAD

**Issue by matzimowski** [brainly/style-guide#464]
Investigate the issues with flexbox + `flex-basis: 100%` on a child element.
There is a problem that there is no wrap on content when `flex-basis: auto` is set.

It can be reproduced with mint-floating-box component + mint-primary-header on Main Page. You need to remove flex-basis:100% to the `.mint-floating-box .mint-primary-header` and scroll the page to see the effects.

<img width="323" alt="screen shot 2015-10-22 at 15 32 25" src="https://cloud.githubusercontent.com/assets/1231144/10666910/b04a3bb8-78d4-11e5-9cfb-dd0f2af0cb57.png">

It would be cool to be able to reproduce it on jsfiddle and report to https://github.com/philipwalton/flexbugs

**Comment by vergilius** [comment]
Looks like it's not an issue anymore cc @matzimowski
