### ISSUE TITLE
[IE] remove line-height: rhythm(1.5) from mint-input--low

### ISSUE THREAD

**Issue by matzimowski** [brainly/style-guide#467]
There is an issue that placeholder is not centered in `mint-input--low`.

<img width="253" alt="screen shot 2015-10-22 at 16 20 01" src="https://cloud.githubusercontent.com/assets/1231144/10667668/cc5648ca-78d8-11e5-92e9-a67d3211feef.png">

**Comment by aju** [comment]
After changing input sizes it is no longer valid
