### ISSUE TITLE
[IE + Chrome] Change select to have height calculated based on border

### ISSUE THREAD

**Issue by matzimowski** [brainly/style-guide#468]
The effective `<select>` height should be `32px`, line-height should be `34px`.

Basically, the `fitText` mixin should be applied to fix font centering across browsers.

chrome:
<img width="218" alt="screen shot 2015-10-22 at 16 30 44" src="https://cloud.githubusercontent.com/assets/1231144/10668126/091cc8ae-78db-11e5-926c-e448808831e7.png">

ie:
<img width="202" alt="screen shot 2015-10-22 at 16 31 05" src="https://cloud.githubusercontent.com/assets/1231144/10668128/0e344a92-78db-11e5-8c7e-23f3a6cf4390.png">

**Comment by aju** [comment]
I can see this issue after selects update
