### ISSUE TITLE
mint-icon-as-button--xxsmall

### ISSUE THREAD

**Issue by kdzwinel** [brainly/style-guide#473]
Cookie policy close button is 18x18px

<img width="301" alt="screen shot 2015-10-23 at 15 16 35" src="https://cloud.githubusercontent.com/assets/985504/10693538/205181ae-7999-11e5-8390-0757591cd9d9.png">

**Comment by vergilius** [comment]
after last update its 24x24

**Comment by vergilius** [comment]
we don't need it annymore
