### ISSUE TITLE
Messages panel on header

### ISSUE THREAD

**Issue by JanuszSzewczyk** [brainly/style-guide#477]
What do you think to move "Inbox" button like on picture:
![image](https://cloud.githubusercontent.com/assets/13464120/10754075/8d5c9d52-7c95-11e5-8be5-b46e2beab47f.png)
It's similar function to search in "Friends panel". I think this look better

**Comment by JoannaWalusiak** [comment]
![empty-messages](https://cloud.githubusercontent.com/assets/13762510/10756052/d3a5ffe0-7ca1-11e5-8a3a-0b96498e9fe5.png)
:+1: janusz
and Button should be Secondary button small inverted

**Comment by JanuszSzewczyk** [comment]
But I will give different copy... closer to CTA: "GO TO INBOX"

**Comment by aju** [comment]
@JanuszSzewczyk please move this issue to symfony
