### ISSUE TITLE
Placeholder and text in input fields are not centered

### ISSUE THREAD

**Issue by mr-mig** [brainly/style-guide#508]
The issue is repro all the time.

![image](https://cloud.githubusercontent.com/assets/1062491/10912223/c03c897c-8248-11e5-86e4-24fb84cffcb8.png)

Apparently there’s no nice solutions apart from hack: showing the small input inside the box with border (like in good old times)  to make text centered.

It will be a breaking change

**Comment by mr-mig** [comment]
Also, textareas and select are affected.
You can play with it here: http://jsfiddle.net/yc11jt6j/100/

**Comment by vergilius** [comment]
Too minor to focus , cc @matzimowski
