### ISSUE TITLE
Fix travis setup in yo/react branch

### ISSUE THREAD

**Issue by mr-mig** [brainly/style-guide#535]
Things to fix:

- [x] scss-lint should pass
- [x] tests should run
- [x] eslint should pass

**Comment by mr-mig** [comment]
eslint config can be taken from here: https://github.com/yetu/controlcenter
It is an udated copy of AirBnB code style

**Comment by azakordonets** [comment]
Here's a list of recommended rules from Eslint org itself - http://eslint.org/docs/rules/

**Comment by azakordonets** [comment]
I'm currently working on adding eslint to the project

**Comment by azakordonets** [comment]
Pull request is created - https://github.com/mr-mig/style-guide/pull/2

**Comment by mr-mig** [comment]
Fixed in https://github.com/brainly/style-guide/pull/603
