### ISSUE TITLE
Remove `--not-responsive` move to option like large-only@mint-text-bit--to-xxlarge

### ISSUE THREAD

**Issue by aju** [brainly/style-guide#606]
WDYT?

**Comment by vergilius** [comment]
**please describe your ideas in description field, not title**

its ok for me

**Comment by aju** [comment]
@vergilius  :P
`aju commented on 3 Dec 2015`

**Comment by vergilius** [comment]
@aju poor excuse

**Comment by aju** [comment]
@vergilius @kdzwinel @matzimowski so we are not using this schema - we should not use informations about media queries in selectors or modifiers

**Comment by matzimowski** [comment]
OK
