### ISSUE TITLE
Vertically centered icon in label

### ISSUE THREAD

**Issue by matzimowski** [brainly/style-guide#629]
```
.mint-label__icon {
  align-items: center;
}
```

**Comment by kdzwinel** [comment]
we need to also add `flex-basis: 0;` because otherwise icon grows:

<img width="177" alt="screen shot 2016-03-15 at 17 08 43" src="https://cloud.githubusercontent.com/assets/985504/13784753/bd6ec818-ead0-11e5-8de9-e3a9c00c448c.png">

**Comment by aju** [comment]
flex-grow: 0 ?

**Comment by kdzwinel** [comment]
didn't work. I had to do `flex: 0` which, in this case, translates to `flex-basis: 0`

**Comment by kdzwinel** [comment]
<img width="212" alt="screen shot 2016-03-17 at 16 13 16" src="https://cloud.githubusercontent.com/assets/985504/13863053/558662ec-ec97-11e5-90c2-b7f634dc4c46.png">
Safari :( Soo... `flex-basis: 0` is also a bad solution, please ignore.

**Comment by kdzwinel** [comment]
turns out this icon was meant to be 24px, so `flex-shrink: 0` did a job. To sum up:

```
.mint-label__icon {
  align-items: center;
  flex-shrink: 0;
}
```
