### ISSUE TITLE
Add mint-link--dark

### ISSUE THREAD

**Issue by vergilius** [brainly/style-guide#653]
add black version of link

**Comment by vergilius** [comment]
used in taskline, cc @JanuszSzewczyk

**Comment by kdzwinel** [comment]
I don't see that being used in WC/Symfony

**Comment by aju** [comment]
@kdzwinel `sg-link--dark` used in symfony task line:   `var TIMELINE_LINK_CLASS_NAME = 'sg-link sg-link--dark';`

**Comment by burakukula** [comment]
I removed this in symfony today.

**Comment by burakukula** [comment]
<img width="804" alt="screen shot 2016-12-16 at 16 35 52" src="https://cloud.githubusercontent.com/assets/4272331/21268130/c1622a4e-c3ad-11e6-8f98-f97a537122b1.png">

**Comment by kdzwinel** [comment]
very good comment by me. Close it.
