### ISSUE TITLE
Watch command breaks icons when jekyll docs are rebuilt

### ISSUE THREAD

**Issue by vergilius** [brainly/style-guide#658]
You need to restart server to build everything properly

**Comment by vergilius** [comment]
It breaks every time we do a change

**Comment by aju** [comment]
@vergilius still and issue? can we close this one?

**Comment by vergilius** [comment]
@aju could you check it?

**Comment by kdzwinel** [comment]
Jekyll is gone - feel free to reopen this issue if this is still a problem
