### ISSUE TITLE
Add mint-text-bit--dense

### ISSUE THREAD

**Issue by matzimowski** [brainly/style-guide#672]
`.mint-text-bit--dense {
  line-height: rhythm(1.5);
}`

**Comment by kdzwinel** [comment]
I don't see it being used in WC/Symfo

**Comment by burakukula** [comment]
@matzimowski it is used only one time in symfony. Do we need it in styleguide in this case?

**Comment by aju** [comment]
I would refactor it in symfony and remove this issue

**Comment by burakukula** [comment]
@matzimowski we just removed it from symfony. I close this issue.
