### ISSUE TITLE
Add font-display: optional

### ISSUE THREAD

**Issue by kdzwinel** [brainly/style-guide#751]
https://developers.google.com/web/updates/2016/02/font-display

`font-display: optional` will only wait 100ms for a font and if it won't load, it will show default fonts instead (while font is loading in background). Loaded font will be displayed on the next webpage.

This is not widely supported yet, but support is coming.

Status: https://www.chromestatus.com/features/4799947908055040

**Comment by vergilius** [comment]
We're still waiting

**Comment by kdzwinel** [comment]
Landed in Chrome and Firefox.

**Comment by matzimowski** [comment]
we decided to go with: `font-display: swap;`
"swap: Gives the font face no block period and an infinite swap period."
