### ISSUE TITLE
.sg-icon-as-button--peach

### ISSUE THREAD

**Issue by matzimowski** [brainly/style-guide#833]
```
.sg-icon-as-button--peach {
  &.sg-icon-as-button--action-active {
    background-color: $peachPrimary;
  }
}
```

**Comment by aju** [comment]
@matzimowski I think its no longer valid - please confirm

**Comment by matzimowski** [comment]
@aju i cannot find any reference, probably no longer valid. i am closing it.

**Comment by kdzwinel** [comment]
This is apparently used in challenges on the "Failed" message. You can find the definition in the symfony / fixme file
