### ISSUE TITLE
unsplash.it is not working correctly

### ISSUE THREAD

**Issue by burakukula** [brainly/style-guide#872]
Maybe we can look for some alternative.

**Comment by kdzwinel** [comment]
HA! I was about to report that. Use this:

https://source.unsplash.com/240x240/?cat

(to avoid loading same image multiple times set random search queries `?some-random-word`)

**Comment by burakukula** [comment]
YEAH!! Should we close this issue?

**Comment by kdzwinel** [comment]
I've fixed that in ui-components, it still has to be fixed here :)

**Comment by burakukula** [comment]
I will take care of that.

**Comment by kdzwinel** [comment]
🙌
