### ISSUE TITLE
Improvement of placeholders on mobile

### ISSUE THREAD

**Issue by burakukula** [brainly/style-guide#909]
![screenshot_20161230-165118](https://cloud.githubusercontent.com/assets/4272331/21567908/485dc0fa-ceb0-11e6-9ed0-890d3047b7fb.png)

**Comment by burakukula** [comment]
Maybe we could solve this like that? WDYT @aju @vergilius @matzimowski @kdzwinel ?

<img width="359" alt="screen shot 2017-01-04 at 12 29 25" src="https://cloud.githubusercontent.com/assets/4272331/21641141/3a040636-d27a-11e6-995b-275ede091c95.png">

**Comment by aju** [comment]
@burakukula please verify with Karol, I think its better

**Comment by kdzwinel** [comment]
Design has changed. Is that still a problem?

<img width="469" alt="screen shot 2017-07-26 at 11 18 11" src="https://user-images.githubusercontent.com/985504/28613904-2fd2eb40-71f4-11e7-97e4-48e18275d2ee.png">

**Comment by anna-wro** [comment]
https://github.com/brainly/symfony/pull/4743/
