### ISSUE TITLE
two-column layout issue on safari

### ISSUE THREAD

**Issue by matzimowski** [brainly/style-guide#967]
it fixes two-column layout issue on safari, needs some investigation
related to change: https://github.com/brainly/style-guide/pull/959
```
.sg-layout__content {
  @include sgBreakpoint(large-only) {
    flex-basis: 66%;
  }
}
```

**Comment by kdzwinel** [comment]
@matzimowski can you create a JSBin so it's easy to test?

**Comment by burakukula** [comment]
@matzimowski verified and it's not appearing any more. I am closing this issue.
