### ISSUE TITLE
sg-textarea--nested

### ISSUE THREAD

**Issue by vergilius** [brainly/style-guide#996]
used in messages (autosized textarea)

```
.sg-textarea--nested {
  display: flex;
  border: none;
  border-radius: 0;
  padding: rhythm(0.104) 0; // no idea why such value was picked - investigate before implementation
  height: rhythm(1);
  width: 100%;
}

```

**Comment by kdzwinel** [comment]
There is no `--nested` anymore: https://github.com/brainly/style-guide/blob/master/src/components/form-elements/_textarea.scss

**Comment by burakukula** [comment]
It is still used in brainly-frontend. I guess we would need to add this option to textarea at the end.
